### ISSUE TITLE
Explicit support for BigchainDB 2.0

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/aquarius#106]
Right now, the `oceandb-bigchaindb-driver` Python package isn't part of the installation requirements of `ocean-aquarius` (i.e. the Aquarius Python package).

It's not clear if Aquarius would work with BigchainDB 2.0. See https://github.com/oceanprotocol/oceandb-bigchaindb-driver/issues/22

**Comment by eruizgar91** [comment]
This is out of date.
