### ISSUE TITLE
 Bug in trigger_caching Function Prevents Extraction of chainId

### ISSUE THREAD

**Issue by 3xz1** [oceanprotocol/aquarius#1097]
**Describe the bug**
The bug occurs in the  `aquarius/app/assets.py` `trigger_caching` function of the application. When attempting to extract the `chainId` from the request payload, the code incorrectly uses the key `chain_id` instead of `chainId`, leading to failure in retrieving the expected value.

**To Reproduce**
1. Send a request to trigger the caching feature.
2. Include a JSON payload with the correct structure, but use `"chain_id"` instead of `"chainId"` for the key corresponding to the chain ID.
3. Observe that the function fails to extract the `chainId` from the payload.
4. Consequently, the function returns an error response indicating an invalid `chainId`.

**Expected behavior**
The `trigger_caching` function should successfully extract the `chainId` from the request payload and proceed with the caching process.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The issue arises due to a mismatch between the key used to access the `chainId` value in the request payload and the actual key present in the payload schema. The correct key to access the `chainId` value is `"chainId"`, but the code erroneously uses `"chain_id"`. This inconsistency causes the function to incorrectly identify the `chainId` as missing, leading to the error response being returned to the user.

To resolve this issue, the code should be updated to use the correct key, `"chainId"`, when extracting the `chainId` value from the request payload.

**Comment by mihaisc** [comment]
Component deprecated by Node
