### ISSUE TITLE
Swagger spec file errors

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#110]
## Expected Behavior

I want to read in the json spec file generated by Swagger and get a consistent data structure without any errors.

## Current Behavior

The json file uses a field `example` which seems to be non-standard, not displayed in Swagger UI, and which produces errors when importing the spec file into https://editor.swagger.io. This `example` field returns different data structures, sometimes an integer, sometimes an object, making it almost impossible to use and iterate over that data.

## Failure Information (for bugs)

Error from https://editor.swagger.io, mainly:

```
Semantic error at paths./api/v1/aquarius/assets/ddo/query.get.parameters.1.example
'example' field is not allowed in parameter
```

<img width="584" alt="screen shot 2018-11-27 at 13 51 54" src="https://user-images.githubusercontent.com/90316/49083221-4db5da80-f24c-11e8-83ec-d9b61d2e1d43.png">

## Step to Reproduce the problem

1. run Aquarius locally, go to http://0.0.0.0:5000/spec
2. save that blob to some file and import to https://editor.swagger.io
3. watch some cool errors

### Possible Solution

Remove the `example` field?

**Comment by ttmc** [comment]
I thought the example was used when trying out the API in the page generated by Swagger UI. For example, isn't it used if you do an example of registering a new asset? Or is some other example used?

**Comment by kremalicious** [comment]
this is the only place I found this being output and it's basically wrong, producing a 500 server error when trying to execute. If at all, the example should then always be a string:

<img width="1183" alt="screen shot 2018-11-27 at 14 18 50" src="https://user-images.githubusercontent.com/90316/49084355-87d4ab80-f24f-11e8-927b-37e90f00032a.png">

**Comment by kremalicious** [comment]
Over on the docs site this is then producing this error:

```bash
warning There are conflicting field types in your data. GraphQL schema will omit those fields.
SitePage.context.json.paths./api/v1/aquarius/assets/ddo/query.get.parameters[].example:
 - type: number
   value: 100
   source: 7374ebf2-d961-52ee-92a2-c25e7cb387a9
 - type: object
   value: { value: 1 }
   source: 7374ebf2-d961-52ee-92a2-c25e7cb387a9
SitePage.context.json.paths./api/v1/brizo/services/access/initialize.post.parameters[].schema.required:
 - type: array<object|string>
   value: [ 'did', ..., { consumerAddress: null } ]
   source: 7374ebf2-d961-52ee-92a2-c25e7cb387a9
OpenApiSpecPath.parameters[].schema.required:
 - type: array<object|string>
   value: [ 'did', ..., { consumerAddress: null } ]
 - type: array<string>
   value: [ 'asset_did', ... ]
OpenApiSpecPath.parameters[].example:
 - type: number
   value: 100
 - type: object
   value: { value: 1 }
```

**Comment by kremalicious** [comment]
Working with the sample pet store file from Swagger and all is working as expected with that https://petstore.swagger.io powered by https://petstore.swagger.io/v2/swagger.json

With that json, I get no errors:

<img width="1207" alt="screen shot 2018-11-28 at 11 38 06" src="https://user-images.githubusercontent.com/90316/49146268-16a20080-f302-11e8-8044-04014ee37029.png">

**Comment by ttmc** [comment]
I'll ask if we can pivot into becoming a petstore.

**Comment by ttmc** [comment]
Different instances of Aquarius (or Brizo) will have different root URLs, but the same set of endpoints (i.e. the same set of options for the stuff after the port number). That's why the root URL isn't considered part of the API.
