### ISSUE TITLE
Potential for MongoDB injection attacks

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/aquarius#127]
This issue was noted by an external party.

Aquarius gives the users ability to use advanced MongoDB queries right from the REST
interface. This is highlighted as an advantage in the documentation of squid-py library in the following
manner;

**Here, OceanDB instance of mongodb can leverage power of mongo queries in ‘query’
attribute. For more info - https://docs.mongodb.com/manual/reference/method/
db.collection.find**

[Link](https://squid-py.readthedocs.io/en/latest/api/squid_py.ocean.ocean.html?highlight=mongo#squid_py.ocean.ocean.Ocean.search_assets)

Aquarius and all the related libraries (including oceandb_driver_interface and oceandb-mongodb-
driver) pass the incoming query object [directly to MongoDB without sanitization](https://github.com/oceanprotocol/oceandb-driver-interface/blob/develop/oceandb_driver_interface/search_model.py). However this could
prove to be an attack surface, as MongoDB injection attacks are known to exist that could be viable to
execute in this query functionality. For further info and investigation, please check the related
documentation and [guidelines on OWASP Foundation web page](https://www.owasp.org/index.php/Testing_for_NoSQL_injection).

**Comment by eruizgar91** [comment]
Done. We are allowing only some custom queries now.
