### ISSUE TITLE
Add support for the following queries

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/aquarius#140]
We are going to need to implement the following preconfigured queries:

- Price from/to
- License(none, Public Domain, CC BY, CC BY-SA, CC BY-ND, CC BY-NC, CC BY-NC-SA, CC BY-NC-ND)
- Category
- Type(dataset, algorithm, container, workflow, other)
- Update frequency(seldom, annually, quarterly, never)
- Time added(Last week, last month)
- Filter by the condition of have sample.

**Comment by MarcusJones** [comment]
Nice to have: Regex search on key and value. Basically, flatten the dict completely, and match key. If key match, match value. Here's a quick and ugly pseudo-code sketch. 

```
let key_regex = a python regex string
let value_regex = a python regex string
let metadata_attribute = one of [base, additional attributes,  curation] # To cover the main objects of OEP8

function recursive_key_search(key=metadata_attribute) {
    for subkey in metadata[key] {
        if metadata[key][subkey]  == type(dict): 
               recursive_key_search(subkey)
        elif: 
               metadata[key][subkey]  == type(dict): # iterate over list, return match if value_regex == value
        else: 
               return match if value_regex == value
    }
}


```
