### ISSUE TITLE
Add Plecos as a dependency, validate all incoming JSON DDO Metadata

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/aquarius#142]
https://github.com/oceanprotocol/Plecos 

In PyPI: https://pypi.org/project/plecos/

Validate the metadata previous to be write in OceanDB.

Wait for latest version (0.5.0 incoming)

**Comment by ssallam** [comment]
Seems to be completed, when publishing or updating a DDO, the incoming ddo json gets validated by plecos according to the current ddo schema version.
