### ISSUE TITLE
XSS attacks vulnerability

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/aquarius#158]
## Failure Information (for bugs)
The system is vulnerable to reflected cross-site scripting (also known as XSS) attacks. This vulnerability stems from missing validation of the input incoming from the client-side and missing encoding of the output derived from the received input. 

### Possible Solution

• Always encode untrusted data (all parameters which are submitted to the server and then rendered as part of the web page) prior to including it in web pages. The type of encoding should be selected according to the context in which the data is inserted, e.g. HTML element, HTML attribute, JavaScript code, etc;

• HTML encoding should at minimum target the following characters: ' (single quote), " (double quote), > (greater than), < (lesser than), & (ampersand), / (forward slash) and \ (backslash). Note that this will depend on the context.
## Specifications

More info here: https://app.cobalt.io/bigchaindb/ocean-protocol-api-201902/findings/1

**Comment by trentmc** [comment]
Closed because it's on main ocean website which has no assets at risk; it hasn't been an issue in the 2 years since reported; and the link is firewalled. Where things _really_ matter is Ocean Market, Aquarius, Provider but that's outside the scope of this report.
