### ISSUE TITLE
Possible DoS scenario due to missing user input validation

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/aquarius#161]
## Failure Information (for bugs)
Aquarius provides an off-chain database store for metadata about data assets. The Aquarius API allows user to create the assets with a varienty of information inside. For this particular case an end-user is able to register DDO of a new asset using 'POST /api/v1/aquarius/assets/ddo' request.

During the security review the consultants were able to figure out that API doesn't limit end-user with data input, e.g. the DDO asset can contain a large metadata data.

### Possible Solution

- It is recommended to set the maximum size of data that can be send and retrieved from the server, e.g. 50kb;

For more info go here: https://app.cobalt.io/bigchaindb/ocean-protocol-api-201902/findings/3

**Comment by ttmc** [comment]
I think that in production, you'd put something like NGINX or Cloudflare in front of Aquarius and that's probably where you'd put the limit on HTTP request body size (not in the Aquarius configs or code itself). That way Aquarius would not be spending time pre-screening requests.

Maybe the solution is to document that in Aquarius "Production Deployment Recommendations".

Limits can also be put on other things, such as the number of requests per second.

**Comment by aaitor** [comment]
Agree with @ttmc , this can be resolved in the Reverse Proxy configuration. Assigning to @jcortejoso

**Comment by eruizgar91** [comment]
I think that we are aware of that in our NGINX configuration. Close it if it is done @jcortejoso
