### ISSUE TITLE
Add API documentation to the ocean docs page

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/aquarius#172]
Make the documentation more prominent; 

https://github.com/oceanprotocol/aquarius/tree/develop/docs

Has a lot of useful info, but difficult to find. Add this to: 

https://docs.oceanprotocol.com/references/aquarius/

**Comment by ttmc** [comment]
While this idea might seem simple, it's unlikely to get resolved quickly because it relates to a bigger question of how and where to document the various APIs and software... a question that is currently unresolved.

Related pull request: https://github.com/oceanprotocol/docs/pull/207

**Comment by ttmc** [comment]
Note: Matthias and I decided to leave information about getting the API docs of a local instance in the GitHub repository, rather than having that on the docs website.

**Comment by kremalicious** [comment]
@MarcusJones API docs on docs.oceanprotocol.com have been updated.

As for https://github.com/oceanprotocol/aquarius/tree/develop/docs/, it's a bit redundant:

- `for_api_users/`: present on docs API references section
- `for_aquarius_devs/`: this should be in the main readme
- `for_operators/`: is empty, and probably should be a tutorial in the docs

So I would suggest adding the contents of `for_aquarius_devs/` to the main readme, then remove the `docs/` folder?
