### ISSUE TITLE
Delete the file API.md? or the whole docs/ folder (with some content moved)?

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/aquarius#173]
The file at `/docs/for_api_users/API.md` probably doesn't need to exist any more, because there are now Aquarius API docs at https://docs.oceanprotocol.com/references/aquarius/

Keeping that file up-to-date is just an extra hassle we don't need.

If that file does get deleted, then don't forget to remove references to it, e.g. from `/docs/for_api_users/README.md`

**Comment by kremalicious** [comment]
I think the whole `docs/` folder is redundant, see my comment from 5 sec. ago :-) https://github.com/oceanprotocol/aquarius/issues/172#issuecomment-484051723
