### ISSUE TITLE
search: ascending & descending sort order

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#179]
When searching based on a date (e.g.) latest published assets, the sort order needs to be descending. It looks like Aquarius' `/ddo/query` endpoint does not support switching the sort order, and defaults to ascending order, meaning the results with the highest match are returned last.

That should be addressed by adding a new `order` key to the search query, allowing to have `desc` & `asc` as values. And a descending order should be the default, meaning the results with the highest match should come first.

From js, a search query for getting assets by date published starting from the most recent published one could look like this:

```js
const query = {
    text,
    page: 1,
    offset: 100,
    query: {
        value: 1
    },
    sort: {
        datePublished: 1
    },
    order: {
        desc: 1
    }
}
```

**Comment by jernejpregelj** [comment]
https://github.com/oceanprotocol/aquarius/issues/181
