### ISSUE TITLE
search: can't sort by dateCreated or datePublished

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#180]
Using this query does not sort by `datePublished`, has no effect whatsoever on the sorting of the results:

```js
const query = {
    offset: 25,
    page: 1,
    sort: {
        datePublished: 1
    }
}
```

**Comment by jernejpregelj** [comment]
Workaround is:

“sort”: {
   “created”: 1 or -1
}

**Comment by jernejpregelj** [comment]
https://github.com/oceanprotocol/aquarius/issues/181
