### ISSUE TITLE
validate categories & price for commons marketplace

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#189]
The categories in the Commons are highly curated and fixed and we need to prevent people not going through the UI to use the correct categories.

So when people push assets into the Aquarius instance for the commons marketplace, we need to check the categories against a fixed list. If there's not a much, provide an error message with a link to the list of categories.

At the time of writing, this master list is this one https://github.com/oceanprotocol/commons/blob/master/client/src/data/form-publish.json#L40

Another thing is to enforce a price of 0 for every asset pushed into the Commons Aquarius instance.

**Comment by alexcos20** [comment]
it's going to be solved in the new version, which allows auth
