### ISSUE TITLE
Support the enabling/disabling creation of non-free assets

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/aquarius#201]
In order to support Marketplaces with only free assets, it would be necessary to support the configuration of Aquarius restricting the creation of assets where the price is not equal to zero.
The configuration to add should be:

```
allowFreeAssetsOnly= true|false
```

The default value of this configuration must be `false`. If the property is not specified the default behavior must be allowing all kind of prices in Assets creation.
Only when this property exists and the value is true, the creation of new Assets with a price != 0 must be restricted.

If the creation of non free assets is restricted, and during the creation is sent a DDO with price != 0 is sent, aquarius must return a `HTTP 400 Bad Request` response, and in the text response saying:
`Priced assets are not supported`

**Comment by ttmc** [comment]
As a general rule, it's usually a bad idea for a configuration setting to be a double negative, because that makes it more difficult to reason about. Therefore I would suggest using:

```text
allowFreeAssetsOnly= true|false
```

instead.

**Comment by aaitor** [comment]
@ttmc , description changed with the param name suggested.

**Comment by eruizgar91** [comment]
Done!
