### ISSUE TITLE
After re-ordering service items in the DDO service list the serviceDefinitionId is not updated

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/aquarius#208]
## Expected Behavior

After re-ordering the service list in the DDO. 

https://github.com/oceanprotocol/aquarius/blob/ad716ae18e0fa5e9556ea1d43056470ab3cfee04/aquarius/app/assets.py#L778

Since Aquarius is using the _serviceDefinitionId_ field to directly index a service in the services list in the DDO.

I would expect that the _serviceDefinitionId_ to also be correctly assigned, so that
```ddo['service'][serviceDefinitionId]``` will work.

## Current Behavior

```
service = {
    {
       'serviceDefinitionId': 0,
       'type': 'authorziation',
    },
    {
       'serviceDefinitionId': 1,
       'type': 'metadata',
    },
}
```

after re-order, the 

```
service = {
    {
       'serviceDefinitionId': 1,
       'type': 'metadata',
    },
    {
       'serviceDefinitionId': 0,
       'type': 'authorziation',
    },
}
```

### Possible Solution

Assign the 'serviceDefinitionId' when re-ordering the service items.

## Specifications

Aquarius - v0.3.7

**Comment by ssallam** [comment]
`serviceDefinitionId` does not need to match the order of the service in the list. It's more like a unique identifier of a specific service.

**Comment by billbsing** [comment]
I found this out by re-registering a DDO from aquarius. 

Since aquarius uses the serviceDefinitionId as an index into the list not by searching the list for the serviceDefinitionId.

i.e.
```
service[serviceDefinitionId]
```
instead of ..

``` 
for index, item in enumerated(service):
     service[index]
```

**Comment by ssallam** [comment]
This has been fixed in latest Aquarius release.
