### ISSUE TITLE
add consolidated metadata to search response

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#223]
To allow advanced search results filtering, Aquarius should return some consolidated metadata of all search results, across pagination.

### Proposal

```
{
    "results": [],
    "resultsMetadata": {
        "categories": [
            {
                "name": "Category",
                "count": 3
            }
        ],
        "license": [
            {
                "name": "Public Domain",
                "count": 3
            }
        ]
    },
    "page": 1,
    "total_pages": 1520,
    "total_results": 1520
}
```

From https://github.com/oceanprotocol/commons/pull/183#issuecomment-564924835

**Comment by trentmc** [comment]
If this is desirable in the new context of Ocean Market, it will rear its head. Closing in the meantime.

**Comment by kremalicious** [comment]
well yes, this was never done and is crucial if Aquarius stays our search backend. We need all tags as an example, as seen on the linked issues.

**Comment by trentmc** [comment]
Thanks for highlighting.
