### ISSUE TITLE
Prevent publishing into aquarius

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#227]
We need to have a validation scheme for every asset that gets published into aquarius, in order to prevent malicious or unallowed content.

Alice it's the owner of a Marketplace and it's running her instances of Marketplace, aquarius, brizo. The content is highly curated, careful picked and obeys a commission schema. Also, Alice has invested a lot in marketing and promoting the Marketplace.
Bob is a malicious actor, that starts pushing content into Alice's Aquarius, trying to lower his reputation.

Purposal:
- have a validating list, with attributes that must be obeyed by the published DDO. We can use regex to validate each attribute

(extension of #189 )

**Comment by kremalicious** [comment]
All validation is already done by plecos https://github.com/oceanprotocol/Plecos 

Is this issue here asking for a customization of that validation?

**Comment by alexcos20** [comment]
No, this is about an extra validation done in Aquarius

**Comment by alexcos20** [comment]
superseeded by #275
