### ISSUE TITLE
Allow DDO creation/update from on-chain events

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#265]
- [x]  Allow DDO creation from on-chain events
- [x]  Allow DDO update from on-chain events
- [x]  Allow db rebuild from scanning all on-chain events
- [x]  Allow compressed  DDO
- [x]  Allow private encrypted DDO
- [x]  Allow administrator to decide if on-chain/off-chain DDOs are allowed (choose one or both)
- [x]  Allow administrator to decide if encrypted/public DDOs are allowed (choose one or both)
- [ ]  Allow a list of allowed publishers

**Comment by ssallam** [comment]
This is ready in release v2.0.0, merge to Master will be deferred until the V3 release
