### ISSUE TITLE
Incorrect total pages from query

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#299]
## Expected Behavior

I am calling `https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo/query` with `offset: 21
page: 3
query: {}
sort: {created: -1}`
Currently there are 43 `totalResults`, i should get an array with one element

## Current Behavior

On the 3rd page i get an empty array
`{"results": [], "page": 3, "total_pages": 3, "total_results": 43}`

## Failure Information (for bugs)

`totalResults` are incorrect or there the enpoint doesn't return the correct items for the last page

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. http post with the details specified at `Expected Behaviour`

* Version: 2.1.0

**Comment by ssallam** [comment]
The extra documents have been remove, please verify.

**Comment by mihaisc** [comment]
It's ok now, thanks

**Comment by ssallam** [comment]
Doing the same search, total results is 238, pages is 12, the last page has 7 items.
