### ISSUE TITLE
Price is incorrect on ddo

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#300]
## Expected Behavior

Calling https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo/did:op:70744b434960c934BC50de3Bf63F79E2CfBb8503
should return `"price": {"datatoken": 0.0, "ocean": 0.0, "value": 0, "type": "", "address": "0x608d05214E42722B94a54cF6114d4840FCfF84e1", "pools": []}`

## Current Behavior

The call returns `"price": {"datatoken": 0.0, "ocean": 0.0, "value": 2000.0, "type": "exchange", "address": "0x608d05214E42722B94a54cF6114d4840FCfF84e1", "pools": []}`

## Failure Information (for bugs)

When I call ` await ocean.fixedRateExchange.searchforDT(dataTokenAddress, '1' )`  (where `dataTokenAddress` is `0x70744b434960c934BC50de3Bf63F79E2CfBb8503` )  i get no fixed rate exchanges

**Comment by ssallam** [comment]
Is this still an issue? so much changed during the past days.

**Comment by mihaisc** [comment]
We can close this, it didn't happen on any other ddo
