### ISSUE TITLE
Have `text` query search in whole DDO

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#304]
It seems a `text` query only searches through selected metadata service attributes. I started sending more fine-grained search queries but it's not scalable to detect what exactly users input into the search field, I started doing that with the owner here https://github.com/oceanprotocol/market/pull/187/files#diff-9579933ab985f95c6d94d54a6eb3476017c0c4ad58906c942c9ddaf7c6616696R13

But this is not cool, cause users might also search for datatoken address so it's impossible to know what users exactly search for.

So the `text` query needs to be more fuzzy and if I search for datatoken name, symbol or address should return something so front-end does not need to create dedicated queries for each and every attribute.

As of right now I see the main use cases users request to search for so as a start we can make all them indexable:
- publisher address
- author
- datatoken name
- datatoken symbol
- datatoken address
- pool address (no priority)

**Comment by ssallam** [comment]
text search now works on mainnet.
