### ISSUE TITLE
Purgatory metadata in DDO

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#313]
For the purgatory feature we need the following fields on the ddo (similar to price). We need to be able to filter our queries to hide assets that have `isInPurgatory = true`
```
isInPurgatory: boolean
purgatoryData: {
       did: string,
       reason: string

}
```
To get this info you can either directly check the list https://raw.githubusercontent.com/oceanprotocol/list-purgatory/main/list-assets.json or query the endpoint https://market-purgatory.oceanprotocol.com/api/asset?did=did:op:0000

**Comment by ssallam** [comment]
* Grab the purgatory list once an hour 
* Compare with previous list
* If list is updated then run an update on the listed DDOs

**Comment by trentmc** [comment]
Q: I'm wondering, maybe we don't need 'date' field? there's already date info on blockchain and on github.com

**Comment by ssallam** [comment]
This is already in Aquarius, pending verification and deployment.
