### ISSUE TITLE
Replace flask/gunicorn with a more performant framework

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/aquarius#327]
**Is your feature request related to a problem? Please describe.**
When Ocean Market usage was going crazy in Oct 2020, we were hitting the limits of Aquarius. We created [an epic](https://github.com/oceanprotocol/aquarius/issues/323) to track the promising approaches. Our quick solution was to run more replicates of them, and that solved the urgent problem. 

However it's much cleaner, cheaper, and more maintainable to improve the performance of the Aquarius binary itself. In testing, we found that flask/gunicorn was a performance bottleneck.

**Describe the solution you'd like**

Steps:
- [ ] Benchmark the current performance.
- [ ] Double-check that there's at least one unit or system test on using this. If there isn't, build at least one.
- [ ] Survey alternatives to replace flask/gunicorn. Choose the most promising one. Limit time spent here to <1 day
- [ ] In code, replace flask/gunicorn to implement the most promising one
- [ ] Benchmark new performance
- [ ] If still not satisfied, consider implementing a different one

**Describe alternatives you've considered**
In the [scaling epic](https://github.com/oceanprotocol/aquarius/issues/323), we investigated scaling options. This was lower priority. But still worth doing.

There are alternatives in terms of which framework. But that's part of this issue's work itself.

**Comment by alexcos20** [comment]
tornado seems a good alternative, but it's low prio

**Comment by trentmc** [comment]
**Is your feature request related to a problem? Please describe.**
When Ocean Market usage was going crazy in Oct 2020, we were hitting the limits of Aquarius. We created [an epic](https://github.com/oceanprotocol/aquarius/issues/323) to track the promising approaches. Our quick solution was to run more replicates of them, and that solved the urgent problem. 

However it's much cleaner, cheaper, and more maintainable to improve the performance of the Aquarius binary itself. In testing, we found that flask/gunicorn was a performance bottleneck.

**Describe the solution you'd like**
- [ ] The very first thing is to benchmark the current performance.
- [ ] Survey alternatives to replace flask/gunicorn. Limit time spent here to <1 day
- [ ] Make a judgement call, and implement one to replace flask/gunicorn
- [ ] Benchmark performance
- [ ] If still not satisfied, consider implementing a different one

**Describe alternatives you've considered**
In the [scaling epic](https://github.com/oceanprotocol/aquarius/issues/323), we investigated scaling options. This was lower priority. But still worth doing.

There are alternatives in terms of which framework. But that's part of this issue's work itself.

**Comment by AnaLoznianu** [comment]
Closing this as now we have multi-chain aqua. If there is any performance issue, we will address it based on the current architecture.
