### ISSUE TITLE
Deprecate price endpoints

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#329]
Only after market has migrated to GraphQL

- [x] remove pool information from the ddo
- [x] remove FRE (fixed-rate exchange) information from the ddo

**Comment by alexcos20** [comment]
blocked by #324

**Comment by kremalicious** [comment]
not blocked anymore, `market` does not use any of the pool endpoints anymore.

**Comment by TimDaub** [comment]
Just saw this. I'm using https://docs.oceanprotocol.com/references/aquarius/#assetsddo and then I'm filtering the results for where `price.type === "pool"`. Will this be possible in the future, or do I have to move to subgraph too?

**Comment by alexcos20** [comment]
Please try to move all price related thing to subgraph.
Aquarius is going to go back to it's origin: just metadata cache

**Comment by TimDaub** [comment]
OK, for planning. When will this land roughly?

**Comment by alexcos20** [comment]
You can already use the graph, we have support for both pools and Fixed Rate Exchanges

**Comment by TimDaub** [comment]
> You can already use the graph, we have support for both pools and Fixed Rate Exchanges

yes, I understand. But the change on rugpullindex could take one or two days so I'm asking on what date you're planning to remove the price data from acquarius. Is it something I need to take care of today or until next month?

**Comment by alexcos20** [comment]
Take your time, it's not super urgent.  Anyway, we will release a new major version of Aqua, so your instances are not going to be affected (q: do you have a deployment or are you using ours?)

**Comment by TimDaub** [comment]
> you using ours?

I'm using yours: https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo

I'm happy to make changes in the short term. From my perspective, what would be great is if you e.g. told me: "Deprecation notice Ocean Protocol will remove price feeds until at least May 1, 2021. Switch to subgraph as an alternative".

Then I'll take care of switching until that date.

> Take your time, it's not super urgent. 

Is this still valid when using your instance?

**Comment by kremalicious** [comment]
as of now there are no release date plans for this. On `market` we face the same issue, especially not looking forward to figuring out `price.type` via subgraph before rendering anything. In any case, it's safe to assume no Aquarius on any mainnet will be rolled out with this change before the `market` removes its reliance on the last remaining `ddo.price` things.

For that we created a milestone so it probably helps following that. Only after all of them are finished, Aquarius can be updated https://github.com/oceanprotocol/market/milestone/2

**Comment by calina-c** [comment]
On assets that were indexed previously, price fields are empty. On newer ones, no price should be set. Marking as closed.
