### ISSUE TITLE
Price metadata update

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#331]
Price needs to be updated based on [new format ](https://github.com/oceanprotocol/ocean.js/blob/9a861401b753a7ca750a1ab574d760f8d700c18b/src/ddo/interfaces/BestPrice.ts#L5).
In the react hooks `isConsumable` is: 
- for pools
```
const usePrice = await ocean.pool.getOceanNeeded(poolAddress, '1')
isConsumable: Number(usePrice) > 0 ? 'true' : 'false'
```
- for exchanges
```
const dtReserve = cheapestExchangeAddress
      ? await ocean.fixedRateExchange.getSupply(cheapestExchangeAddress)
      : '0'
 isConsumable: Number(dtReserve) > 0 ? 'true' : 'false'
```

When no pool or exchange is found `isConsumable = '' `

**Comment by ssallam** [comment]
https://github.com/oceanprotocol/aquarius/pull/332
