### ISSUE TITLE
Aquarius: Add sample deploy files

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#355]
Create a folder deployment
 - add sample files of how to run the provider as a systemd service
 - add sample files of how to run the provider using docker-compose
 - add sample files of how to run the provider in a k8 enviroment (yaml file)

**Comment by md00ux** [comment]
[Aquarius](https://github.com/oceanprotocol/aquarius) depends on the backend database, which means the database must be deployed first.

In this example we will deploy Elasticsearch as database backend. Templates (yaml) are provided and could be customized based on the environment's specifics. 
More customization parameters could be offered through Helm [chart deployment](https://github.com/elastic/helm-charts/tree/master/elasticsearch).
Additional things to consider on a production deployment - number of replicas, memory heap size, etc. Check the [guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html) for recommended practices.

```
kubectl create ns ocean
kubectl config set-context --current --namespace ocean
kubectl apply -f elasticsearch-master-sts.yaml
kubectl apply -f elasticsearch-master-svc.yaml
kubectl apply -f elasticsearch-master-headless-svc.yaml

kubectl get pods,svc
NAME                         READY   STATUS    RESTARTS   AGE
pod/elasticsearch-master-0   1/1     Running   0          8h
pod/elasticsearch-master-1   1/1     Running   0          8h

NAME                                    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/elasticsearch-master            ClusterIP   172.20.70.12   <none>        9200/TCP,9300/TCP   8h
service/elasticsearch-master-headless   ClusterIP   None           <none>        9200/TCP,9300/TCP   8h

```
