### ISSUE TITLE
Aquarius: Make did index in es case insensitive

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#356]
If you query our mainnet subgraph [here](https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=TransactionHistory&query=%20query%20TransactionHistory(%24user%3A%20String%2C%20%24pool%3A%20String)%20%7B%0A%20%20%20%20poolTransactions(%0A%20%20%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20%20%20where%3A%20%7B%20userAddress%3A%20%24user%20%7D%0A%20%20%20%20%20%20first%3A%201000%0A%20%20%20%20)%20%7B%0A%20%20%20%20%20%20tx%0A%20%20%20%20%20%20event%0A%20%20%20%20%20%20timestamp%0A%20%20%20%20%20%20poolAddress%20%7B%0A%20%20%20%20%20%20%20%20datatokenAddress%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20tokens%20%7B%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20tokenAddress%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D&variables=%7B%0A%20%20%22user%22%3A%20%220x4d156a2ef69ffddc55838176c6712c90f60a2285%22%2C%0A%20%20%22pool%22%3A%20%220xC2B2a49ec5c3a33dAA59FE05d166E6AcCB62f665%22%0A%7D)  you will get datatokens in lower case  .  
Example: 0x5c53218593244b7603b2f1dd47a2fb9367552878
If you are trying to get the dataset from aqua, it will fail:   [here](https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo/did:op:5c53218593244b7603b2f1dd47a2fb9367552878)
When the address is converted to checksum format, works fine:
[here](https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo/did:op:5C53218593244B7603b2F1dD47A2Fb9367552878)

(Technically speaking, this belongs in https://github.com/oceanprotocol/oceandb-elasticsearch-driver , but here has more visibility)

**Comment by kenbodnar** [comment]
The mapping already has a normalizer to make the search into lower case for searching, however, I suspect that it doesn't work because the normalizer filter is for keywords only and not text blocks. Looking into it.

**Comment by ssallam** [comment]
What is the status of this?

**Comment by kenbodnar** [comment]
I created a branch and did a pull request. It needs to be reviewed and merged.

**Comment by ssallam** [comment]
What is the branch or PR? I can't find it

**Comment by kenbodnar** [comment]
The bug was under aquarius but it is an elastic search bug.  The branch:  https://github.com/oceanprotocol/oceandb-elasticsearch-driver/tree/bug/fix_case_insensitive_id_356

**Comment by ssallam** [comment]
This still needs verification.

**Comment by kenbodnar** [comment]
Tested & Verified. Notice that I searched for "145<capital>C" and it correctly returned "145<lowercase>c". The obverse also works.

_Kens-MacBook-Pro-2:aquarius kenbodnar$ curl 'http://localhost:9200/aquarius/_search?q=id:"did:op:145C8961fa147a4147D829de72ef760e0a9d8304"&pretty=true'
{
  "took" : 5,
  "timed_out" : false,  
  "_shards" : {    "total" : 5,    
  "successful" : 5,    
  "skipped" : 0,    
  "failed" : 0  },  
  "hits" : {    
  "total" : 1,    
  "max_score" : 4.321923,    
  "hits" : [      
    {        
     "_index" : "aquarius",        
     "_type" : "_doc",        
     "_id" : "did:op:145c8961fa147a4147D829De72ef760E0a9d8304",        
     "_score" : 4.321923,        
     "_source" : {          
      "@context" : "https://w3id.org/did/v1",          
      "id" : "did:op:145c8961fa147a4147D829De72ef760E0a9d8304",          
      "publicKey" : [            
        {              
          "id" : "did:op:145c8961fa147a4147D829De72ef760E0a9d8304",              
           "type" : "EthereumECDSAKey",              
           "owner" : "0x09A8963e16CB7C94F5cbB2ff38fA1590946b7F51"            
        }          
       ],_
