### ISSUE TITLE
Get asset name/title by did

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#358]
It would be useful to get the asset title by did and not the whole ddo. 
This is useful in many scenarios where we don't need the ddo, like the transactions table or pool shares . In these cases all the data is gathered from the graph, i only need the name of the asset to create a link to it.

![image](https://user-images.githubusercontent.com/26000280/104725269-85d54b80-573a-11eb-8d6c-0c61122e4258.png)
![image](https://user-images.githubusercontent.com/26000280/104725290-8a016900-573a-11eb-8e76-f3877180ec6e.png)

**Comment by ssallam** [comment]
The metadata endpoint returns the metadata without the ddo.
Is this sufficient for the purpose of this issue?

**Comment by mihaisc** [comment]
It's better but still a lot of useless overhead downloaded.

**Comment by alexcos20** [comment]
and have a POST endpoint that accepts a list of did..  It might be usefull
