### ISSUE TITLE
`isConsumable` not set on multiple assets

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#361]
**Describe the bug**
`isConsumable` is not set on most of the more recent assets, couldn't figure out a correlation and since it stopped working ok.

Related to #331

**To Reproduce**
[This asset](https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo/did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38) has the property set correctly

[This one](https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo/did:op:c8773fdBE70D2912Ecb5CEB4e9Bb489F27Feab08) doesn't have it at all, it should be ` "isConsumable": "false"`

Created [this asset](https://market.oceanprotocol.com/asset/did:op:34e0a15FC75b4d75fa658b098140bc27cf36027b) with fixed price, there is enough supply and yet `"isConsumable": "false"`
![image](https://user-images.githubusercontent.com/26000280/105062620-7aa85580-5a83-11eb-8d63-16993e036779.png)

**Comment by trentmc** [comment]
@ssallam to merge

**Comment by ssallam** [comment]
the issue is related to an old asset.
