### ISSUE TITLE
aquarius: Only allow code merges if unit test code coverage ratchets up

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/aquarius#384]
**Is your feature request related to a problem? Please describe.**
We constantly have bug "fixes" where it's just a change to the code, but there are no unit tests. Over time the quality of the sw deteriorates. The excuse is "not enough time" but this is simply untrue because we *do* pay back in spades. Quality comes for free, and then some. So we need to do more tactics to enhance quality. And helping to ratchet up code coverage ratchets up is a good one.

Towards code quality, if we have a constraint where % code coverage must go upwards, it not only prevents code quality from degrading due to missing tests, over time it ratchets the % coverage upwards and therefore quality upwards.

**Describe the solution you'd like**
Only allow a PR to be merged (or a direct commit) if % code coverage doesn't go down.

This is pretty common SW engineering practice. We did it on the bigchaindb code base with good success. Let's do it here.

**Comment by trentmc** [comment]
Suggestion of how to do it:
https://github.com/oceanprotocol/ocean.js/issues/626#issuecomment-784216054

**Comment by kremalicious** [comment]
Same here as [over on ocean.py](https://github.com/oceanprotocol/ocean.py/issues/146#issuecomment-784315423). Seems all python repos use Codacy but I can't find any oceanprotocol repo on there, like this is what the badge in the readme links to: https://app.codacy.com/manual/ocean-protocol/aquarius

**Comment by calina-c** [comment]
Done with CodeClimate.
