### ISSUE TITLE
rename default branch to `main`

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#385]
ocean.py, aquarius, provider are the only repos using `master`. This repo should follow the same pattern as all other repos by using `main` as the default branch:

- rename default branch (GitHub has even interface for that in repo settings), deleting `master` in the process
- if any, update all references to `master` branch to `main`
- make sure to switch default branch in any attached tools, like code quality tools, DockerHub etc.

**Comment by trentmc** [comment]
@calina-c -- I assigned to you given that you're working on this:)
