### ISSUE TITLE
Aquarius should process ExchangeRateChanged events as well

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#403]
**Is your feature request related to a problem? Please describe.**
When a FRE Rate gets updated, aquarius is not caching the new rate.
Code: 
https://github.com/oceanprotocol/aquarius/blob/58546731285379800dc07e9c2f599af75005a6d6/aquarius/events/metadata_updater.py#L198

(we have the event commented, but probably needs additional logic)

Note: FRE = Fixed-Rate Exchange. Ie where the price is fixed, versus AMM

Note: the eth-events repo may be helpful. https://github.com/iamdefinitelyahuman/eth-event

**Comment by mihaisc** [comment]
This is currently blocking the update fixed rate price pr.

**Comment by kenbodnar** [comment]
I am looking at this. since I did the fixed price.address mod changing it to price.exchange_id

**Comment by kenbodnar** [comment]
I am just wondering if there was a reason why ExchangeRateChanged in the event_names array was commented out. It was there before.

**Comment by alexcos20** [comment]
fixed in https://github.com/oceanprotocol/aquarius/pull/439 , but no unit tests
