### ISSUE TITLE
Is aquarius only returning mainchain results?

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/aquarius#418]
Hi,

since there was an announcement recently about OP launching on Polygon too, and since it's currently unclear how you guys will proceed with regards to identifying your data sets (see [here](https://github.com/oceanprotocol/market/issues/431)), I was wondering if my assumption is still valid that Aquarius currently only returns Ethereum main chain assets.

Rugpullindex.com is using `v1/aquarius/assets/ddo`. I'd consider any change to that endpoint, e.g. that it suddenly returns side-chain assets a breaking change that'd require upping the version number. What's your take on that and do I have to prepare for breaking changes?

**Comment by trentmc** [comment]
Marking as a bug, since if it _is_ only returning mainchain results, it's a big issue that needs to be resolved asap.

**Comment by mihaisc** [comment]
This is by design at this point. Each network has its own instance of aquarius/graph/provider.
Eth main - `https://aquarius.mainnet.oceanprotocol.com`
Polygon main - `https://aquarius.polygon.oceanprotocol.com` 
We are working on merging all the network into one metadata cache.

**Comment by TimDaub** [comment]
> This is by design at this point. Each network has its own instance of aquarius/graph/provider.

Ah OK, that's great. I just realized that I've also been using: https://aquarius.mainnet.oceanprotocol.com
OK thanks then this is resolved.
