### ISSUE TITLE
Aquarius `get_asset_ddo(did)` method causes `ResourceWarning: unclosed socket`

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/aquarius#420]
## Expected Behavior

The `get_asset_ddo` method should not cause any warnings.

## Current Behavior

The `get_asset_ddo(did)` method causes `ResourceWarning: unclosed socket` when called via `ocean.assets.resolve`, `ocean.assets.order`, 
and `ocean.assets.download`.

## Failure Information (for bugs)

These warnings were observed during the ocean.py marketplace quickstart.  These warnings do not block the user from successfully completing the quickstart.

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. Run the [ocean.py quickstart marketplace flow](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/marketplace-flow.md)
2. Observe the warnings listed in the Failure Logs section below

### Possible Solution

N/A

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: 2.2.4 (via Barge) 
* Python: 3.8.5
* Solidity: N/A
* JavaScript: N/A
* Node: v10.19.0
* OS: Ubuntu 20.04.2 LTS (Focal Fossa)

## Failure Logs

Listed below are the warnings and the command that caused them.

```console
>>> asset = ocean.assets.resolve(did)
/home/david/projects/test3/venv/lib/python3.8/site-packages/ocean_lib/assets/asset_resolver.py:39: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35064), raddr=('127.0.0.1', 5000)>
  ddo = AquariusProvider.get_aquarius(metadata_url).get_asset_ddo(did)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

```console
>>> quote = ocean.assets.order(asset.did, bob_wallet.address, service_index=service.index)
/home/david/projects/test3/venv/lib/python3.8/site-packages/ocean_lib/assets/asset_resolver.py:39: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35068), raddr=('127.0.0.1', 5000)>
  ddo = AquariusProvider.get_aquarius(metadata_url).get_asset_ddo(did)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

```console
>>> file_path = ocean.assets.download(
...     asset.did,
...     service.index,
...     bob_wallet,
...     order_tx_id,
...     destination='./'
... )
/home/david/projects/test3/venv/lib/python3.8/site-packages/ocean_lib/assets/asset_resolver.py:39: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35092), raddr=('127.0.0.1', 5000)>
  ddo = AquariusProvider.get_aquarius(metadata_url).get_asset_ddo(did)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
signing message with nonce 0: did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15, account=0xBE5449a6A97aD46c8558A3356267Ee5D2731ab5e
```

**Comment by trentmc** [comment]
I'm labeling as a bug because there's a good chance this is due to a bug; better to flag this as such so that it gets priority.

**Comment by calina-c** [comment]
Investigated this and it seems to be related to unit-tests only.
https://stackoverflow.com/questions/48160728/resourcewarning-unclosed-socket-in-python-3-unit-test

I'm going to work on this after we fix issues with higher priority. Do you agree @trentmc?

**Comment by calina-c** [comment]
I am unable to follow the quickstart. @DMats where did you put the test3 directory in the tree? Could the path possibly count?

I get the following error:
![Screenshot 2021-03-26 at 09.00.12.png](https://images.zenhubusercontent.com/5795cf04e40e5714b16c76c5/d77253db-b60b-40dd-9a86-722142815af9)

**Comment by trentmc** [comment]
Something is wonky if it can't see the system level tests directory ./tests

**Comment by DMats** [comment]
I placed `test3` as a sibling of my repositories. The quickstart seemed to execute fine except for the warnings described here.


```
(venv) david@david-Inspiron-5502:~/projects$ ll
total 24
drwxrwxr-x  6 david david 4096 Mar 19 16:06 ./
drwxr-xr-x 33 david david 4096 Mar 25 15:53 ../
drwxrwxr-x  5 david david 4096 Mar 25 09:57 barge/
drwxrwxr-x 15 david david 4096 Mar 19 09:30 market/
drwxrwxr-x 16 david david 4096 Mar 25 15:54 ocean.py/
drwxrwxr-x  4 david david 4096 Mar 19 09:41 test3/
(venv) david@david-Inspiron-5502:~/projects$ cd test3/
(venv) david@david-Inspiron-5502:~/projects/test3$ ll
total 20
drwxrwxr-x 4 david david 4096 Mar 19 09:41 ./
drwxrwxr-x 6 david david 4096 Mar 19 16:06 ../
-rw-rw-r-- 1 david david  360 Mar 19 09:38 config.ini
drwxrwxr-x 2 david david 4096 Mar 19 09:41 datafile.0xDbec339392A8f8074506FDdfACCA0328bd022C15.3/
drwxrwxr-x 7 david david 4096 Mar 19 09:38 venv/
```

**Comment by calina-c** [comment]
Per Trent's suggestion, I will try this again when we release a new ocean.py (we should do that in 1-2 days, after we have the c2d changes to mirror provider)

**Comment by alexcos20** [comment]
blocked by ocean.py new release

**Comment by calina-c** [comment]
@DMats running this with a stable-aqua barge, I can't reproduce the issue. It was probably solved by the changes done inbetween. But I am not sure whether ocean.py or stable-aqua provided the solution. Since you have been running the marketplace flow lately, can you confirm that it is still reproducible using the main barge?

Depending on your answer, we will either close the issue OR mark it as blocked by stable-aqua.

**Comment by DMats** [comment]
@calina-c I was able to reproduce the unclosed socket warnings on the ocean.py main branch while using stable-aqua barge. The unclosed socket warnings occur when running with main barge as well.

**Comment by calina-c** [comment]
Are you sure it's not a system thing? I can not reproduce this on my machine (remote Ubuntu, not Mac). Did you prune docker before running the marketplace flow?

**Comment by DMats** [comment]
@calina Yes I'm sure I pruned before this test. I usually prune it once a day and this was my first test of the day.

Did you use the config.ini file specified by the marketplace flow?

**Comment by calina-c** [comment]
Yes, I used the exact config.ini in the marketplace flow. I followed all the steps precisely. I could not reproduce it :(

**Comment by DMats** [comment]
I have just run the marketplace-flow.md using `main` branch barge and the latest released version of ocean.py in PyPi (v0.5.30). I made sure to prune my docker images before starting. I was unable to reproduce the `ResourceWarning: unclosed socket` warning. Thus, I believe this issue has been fixed and can be closed.
