### ISSUE TITLE
Multi-network aquarius

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#423]
Right now, Aquarius is indexing assets only from one network, specified in config. 
Aquarius should accept a list of networks at start time (specified in config), and it should index assets from all this networks in the same time.

Benefits:
 - Only one instance running
 - Market can display all assets, from all networks, in the same time.
 - Market can search for a particular network using a query

How:
 - Either run multiple events, one for every network (least preferred), or have multiple threads in events_processor (preferred)
- Add chainId to the DDO (as a root object), so the market can know the origin network for each asset.

Issues:
- What if did overlaps ? (IE:  did:op:1 is published on network1, and gets published to network2)  (We don't enforce the did now, this could lead us to problems for sure)  -  always check did + chainId when query for already exists

**Comment by alexcos20** [comment]
Blocked, because in web3.py v4.x there is no web3.eth.chain_id, so we need to bump web3 first

**Comment by alexcos20** [comment]
More technical details

Right now Aquarius expects 3 env:
 - EVENTS_RPC  - where to connect to
- network name
- startBlock
- BLOCKS_CHUNK_SIZE

Instead of expecting that, Aquarius will expect an array of "networks", like:

```
[
   {
      "network":"mainnet",
      "chainId":1,
      "rpc":"http://mainnet",
      "startBlock":0,
      "blocksChunkSize":10000
   },
   {
      "network":"ropsten",
      "chainId":3,
      "rpc":"http://rpc",
      "startBlock":81000,
      "blocksChunkSize":5000
   }
]
```

each element in the array is a network that should be monitored by aquarius.

Elements:
  - network - optional if chainId is used
  - chainId - chainId of the network (optional if network is used)
  - rpc
  - startBlock : optional, this is the deployment block of the MetaDataContract.  Aquarius should start indexing from here, and not from 0 (if specified)
  - blocksChunkSize - how many blocks can be chunked.  highly network dependant

By using network or chainId (one of this has to be defined), Aqua can read ocean-contracts and get the metadata contract address for that network

**Comment by calina-c** [comment]
Integrated in main with stable-aqua merge.
