### ISSUE TITLE
Parsing blocks fails

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#448]
**Describe the bug**
If aquarius is shutdown for a long period, or if it's a fresh install, it will try to parse a large chunk of blocks:
https://github.com/oceanprotocol/aquarius/blob/main/aquarius/events/events_monitor.py#L273

This will probably fail on many networks.

**Expected behavior**
Parsing should be done in chunks no larger than 1000 blocks, in a for loop if the difference is bigger

**Comment by DMats** [comment]
I created the branch https://github.com/oceanprotocol/aquarius/tree/issue448-parse-blocks-in-chunks
