### ISSUE TITLE
Rename `AQUARIUS_URL` envvar

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/aquarius#470]
Rename `AQUARIUS_URL` envvar and `aquarius.url` config option to `AQUARIUS_BIND_URL` and `aquarius_bind_url` respectively.  The motivation is to decouple Aquarius from the `AQUARIUS_URL` envvar and `aquarius.url` config option, which are used by ocean.py.

**Comment by DMats** [comment]
This issue is a follow-on of https://github.com/oceanprotocol/ocean.py/issues/229

**Comment by DMats** [comment]
After a discussion with @alexcos20, we decided to rename `AQUARIUS_URL` to `AQUARIUS_BIND_URL` (instead of `METADATA_CACHE_URI`). We feel this better reflects it's functionality in the context of Aquarius.  The motivation is to decouple Aquarius from the `AQUARIUS_URL` envvar, which is used by ocean.py. 

For this to truly be decoupled, we should *not* implement the same fallback logic that ocean.py uses, so I'm removing that part from the issue description.

**Comment by calina-c** [comment]
@DMats isn't it enough to change the env var name? Why should we also change it's designation in the config? Each Config is different, right?

**Comment by DMats** [comment]
@calina-c That's a fair question. 

Normally, I'd agree that changing only the envvar is sufficient, but multiple ocean components use the same `CONFIG_FILE` envvar to define the config file name which increases the risk that multiple components would read the same `config.ini` file. This behavior is documented here: https://github.com/oceanprotocol/multi-repo-issue/issues/103

I think you came to the same conclusion because I can see that your PR #539 already changes `CONFIG_FILE` to `AQUARIUS_CONFIG_FILE`.
