### ISSUE TITLE
Validate ECIES_PRIVATE_KEY before use

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#477]
**Describe the bug**
At https://github.com/oceanprotocol/aquarius/blob/main/aquarius/app/assets.py#L390 we should also check if ecies_private_key is a valid private key (starts with 0x , correct length, etc)

**Expected behavior**
Block access if the private key is not valid

**Comment by AnaLoznianu** [comment]
Validate using is_address

**Comment by calina-c** [comment]
Checked in util.py
