### ISSUE TITLE
Remove ARTIFACTS_PATH and uses of ContractHandler

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/aquarius#478]
Since the ocean-contracts PyPi package now supports loading contract ABI JSON files using `jsonsempai`, there is some simplification that can be done in aquarius. See for details: https://github.com/oceanprotocol/multi-repo-issue/issues/83#issuecomment-846274680

- [x] Eliminate ARTIFACTS_PATH envvar and artifacts.path config option
- [x] Elimnate uses of ContractHandler

**Comment by calina-c** [comment]
Elimnate uses of ContractHandler: Not Applicable to Aquarius (stable-aqua), since it doesn't use ocean.py anymore. Marking it as done.
