### ISSUE TITLE
Remove ocean.py usages from aquarius

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/aquarius#482]

**Comment by DMats** [comment]
The discussion that spawned this issue can be found in Slack: https://oceanprotocol.slack.com/archives/C01PJ00QE2V/p1621958095021900

**Comment by calina-c** [comment]
Done in stable-aqua and merged to main. The ocean.py dependency was removed and the ocean-contracts dependency was added directly instead.
