### ISSUE TITLE
Purgatory not working properly

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#491]
Version used 2.2.11 on main net
![image](https://user-images.githubusercontent.com/26000280/120621288-6da26680-c466-11eb-81d6-e6b70e8c0cd4.png)

It's not updating the items that are in purgatory.
For example it returns me this item `did:op:f18a471c5553D9E5516c9Fb40910c26B7131068A`  (and many more, this is just an example) https://github.com/oceanprotocol/list-purgatory/blob/cd8151c2133b60d94c9f97b65c4522416ce0bd83/list-assets.json#L971 

And the purgatory list url seems to be hardcoded, it should be configurable.

**Comment by calina-c** [comment]
Closed with #496 when integrated into main.
