### ISSUE TITLE
Datatoken symbol type in es

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#492]
For better searching change `symbol` type from `keyword` to `text`, like `name` is
![image](https://user-images.githubusercontent.com/26000280/120626860-c32d4200-c46b-11eb-83ff-79345dcbf138.png)

**Comment by calina-c** [comment]
We might end up doing it directly in Aquarius after we remove the ES driver (needs testing, PR open: #527).

**Comment by calina-c** [comment]
Done on the branch removing ES driver. https://github.com/oceanprotocol/aquarius/pull/527/commits/c2b9431f31aa82482e3dafc2fbdcf11aa132875c
