### ISSUE TITLE
Sorting by `_score` is not working

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#493]
I am doing the same query in aquarius vs directly in elasticsearch.
Aqua : localhost:5000/api/v1/aquarius/assets/ddo/query
```
{
    "page": 1,
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "product pages",
                        "fields": [
                            "proof.creator",
                            "dataToken",
                            "dataTokenInfo.name",
                            "dataTokenInfo.symbol",
                            "service.attributes.main.name^4",
                            "service.attributes.main.author",
                            "service.attributes.additionalInformation.description",
                            "service.attributes.additionalInformation.tags"
                        ],
                        "default_operator": "AND"
                    }
                },
                {
                    "term": {
                        "isInPurgatory": false
                    }
                }
            ]
        }
    },
    "sort": {
        "_score": -1
    }
}
```

returns the following : 
[aqua_result.txt](https://github.com/oceanprotocol/aquarius/files/6591269/aqua_result.txt)

Elasticsearch : localhost:9200/_search

```
{
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "product pages",
                        "fields": [
                            "proof.creator",
                            "dataToken",
                            "dataTokenInfo.name",
                            "dataTokenInfo.symbol",
                            "service.attributes.main.name^4",
                            "service.attributes.main.author",
                            "service.attributes.additionalInformation.description",
                            "service.attributes.additionalInformation.tags"
                        ],
                        "default_operator": "AND"

                    }
                },
                {
                    "term": {
                        "isInPurgatory": false
                    }
                }
            ]
        }
    },
    "sort": {
        "_score": {"order" : "desc"}
    }
}
```
returns 
[es_results.txt](https://github.com/oceanprotocol/aquarius/files/6591275/es_results.txt)

In aqua response the asset with id `did:op:a2B8b3aC4207CFCCbDe4Ac7fa40214fd00A2BA71` is the last item , while in the es response the last item is the asset with id `did:op:312d24dE83610e351A1977EbA8851CeA8D020e1B`. 
The asset with `did:op:a2B8b3aC4207CFCCbDe4Ac7fa40214fd00A2BA71` is the first item in es response because it has the highest score.

**Comment by calina-c** [comment]
There is some implicit sorting in Aqua. I will look into it.

**Comment by mihaisc** [comment]
Also it seems sorting by `_score` is ignored.

**Comment by mihaisc** [comment]
If no sort is mentioned in the query, the default sort is preserved by aquarius, previously it forced a sort by id. Sorting by `_score` is WIP.

**Comment by AnaLoznianu** [comment]
Hi @calina-c! Any updates on this?

**Comment by calina-c** [comment]
It's done and waiting new tests, last I remember :)
I removed all the mapping for _score

**Comment by AnaLoznianu** [comment]
Do we need the FE team to test this or can we do it and just confirm that everything works as expected?

**Comment by calina-c** [comment]
I will retest this today or tomorrow.

**Comment by calina-c** [comment]
Changed the endpoint name to query instead of ddo/query, to avoid Flask mishaps with wrong endpoint detected. Tested by indexing mainnet and comparing the results from direct ES query and Aquarius query, order is kept.
