### ISSUE TITLE
Remove `resultsMetadata` from result

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#495]
Currently in the result of the queries `api/v1/aquarius/assets/ddo/query` we get  a `resultsMetadata` object that we never use and is inaccurate as well.  I suggest we remove it so we don't do 2 queries in elasticsearch. In the future if we need an aggregate we can just use the same endpoint with a different query.

**Comment by kremalicious** [comment]
haha, I remember that https://github.com/oceanprotocol/aquarius/pull/432

That seemed like prerequisite to get a search filter bar with tags of the displayed search results but yes we never used it so far

**Comment by mihaisc** [comment]
As i've been reading only about elasticsearch the last days 😆  i can tell you we can totally do that, and autocomplete if we want, with queries. We don't need to bundle stuff.
