### ISSUE TITLE
Refactor purgatory

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#496]
Since purgatory has several bugs, and anyway needs to be updated for multi network aqua, I'm proposing the following refactor:

1. Define purgatoryURL as ENV variable
2. Create a function that does the following:

           a) download purgatory using purgatoryURL 
           b) get all did from ES where isPurgatory = true
           c) for each one, check if it's still in a).  if not, update it with isPurgatory = False.  then  pop it from a)   (DID or publisher)
           d) for remaining items in 1, update ES with isPurgatory = True
           e) do that every 1h
3. Call that function at startup & every hour

**Comment by mihaisc** [comment]
Will probably fix https://github.com/oceanprotocol/aquarius/issues/491
