### ISSUE TITLE
Report "Number of orders" for each datatoken

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#500]
Can we have the number of orders for each datatoken? Each asset has multiple services, each service has a datatoken and it would be nice to know how many times each service was ordered and a total orders per asset.

This is useful to create sections like best sellers and give the publisher some quick stats.
For detailed orders and graphs we can fetch the orders from the subgraph.

Watch for startOrder events on the blockchain and when the event is registered, fetch the graph for that asset.
Use a graphQL lib for fetching the graph(doesn't require authentication)

**Comment by calina-c** [comment]
I'm not sure this is a viable solution. I looked into this, and it seems we'd have to watch all the DataTokens for the OrderStarted event. How can we know all the DataTokens? Right now, Aquarius is only watching the Metadata contract events (MetadataCreated and MetadataUpdated). I am not sure how to watch ALL the DataToken contracts, since those are based on a DataToken Template. Any guidance?

**Comment by alexcos20** [comment]
Proposed flow:

- start from https://github.com/oceanprotocol/aquarius/blob/main/aquarius/events/events_monitor.py#L233
1. get ANY datatoken event for that block using web3.eth.filter 
```
event_signature_hash = web3.keccak(text="OrderStarted(address, address, uint256, uint256, uint256, address, uint256)").hex()
event_filter = web3.eth.filter({
    "topics": [event_signature_hash],
   "fromBlock": fromBlock,
  "toBlock": toBlock
    })
```
this will fetch all events with that signature, generated by ANY smartcontract.   There might be the possibility then someone, in their own smartcontract, to have the same exact event, with the same exact parameters, but that smartcontract might not be a datatoken.  That's fine, see below, step 3
2. get event details
3. check if that did exists
4. if so, query subgraph for no of consumes for that datatoken
This step sounds simple, but we should consider the fact that subgraph could be loaded and this block is not yet processed. We have 2 ways of circumventing this:

- simple way:   have a thread , sleep 10 secs, fetch # of consumes
- more exact:  pull subgraph using _metadata object, until last block > our block.  Then we need for sure that the graph is synced

**Comment by AnaLoznianu** [comment]
Blocked by the subgraph

**Comment by mihaisc** [comment]
Quick [example ](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0Atoken(id%3A%220x8fc5d55e1c1197db9c9d28e06033d36ee64cce3f%22)%7B%0A%20%20id%0A%20%20orderCount%0A%7D%0A%7D) of query. Also please rename `consumes` to `orders` (already commented on the docs)
