### ISSUE TITLE
Direct interrogation of elasticsearch

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#501]
I want to be able to pass multiple types of queries like aggregation, autocomplete and other directly to elastic search.
Currently, if I use the following query I should get an aggregated list of tags, but I get a list of assets.
```
"aggs": {
        "my-agg-name": {
            "terms": {
                "field": "service.attributes.additionalInformation.tags"
            }
        }
    }
```

So ideally I would like an endpoint that is just a proxy to es, without changing the response.
- [ ] Add a new simple endpoint to proxy the query to elastic search

**Comment by calina-c** [comment]
Added in `/ddo/es-query`. Marking as closed.
