### ISSUE TITLE
ChainId missing on some DDO's

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/aquarius#511]
**Describe the bug**
The `chainId` field is missing for some ddo's

When searching for all assets I get the following differences on number of assets:
-polygon:   current: 39             multinetwork: 31
-rinkeby:    current: 13645       multinetwork: 13375
-main:        current: 313            multinetwork: 274
-ropsen:     current: 257           multinetwork: 239

Looks like there are assets like this in all the networks

**To Reproduce**
Check the following ddo's on this networks:

- mainnet: did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38, did:op:b07a8bb80242752ce164560ABCb6517DA90a4F65

- rinkeby: did:op:7d1bed95f0292B8C6b2646D493A0d18ab0657e95, did:op:d64243148a2b92289Aa9c7fC31604be68422e6C3, did:op:39d618DEEb5c9Bc11351f7De268133679E167F61

**Expected behavior**
We should have the chainId on all assets

**Comment by alexcos20** [comment]
fixed in https://github.com/oceanprotocol/aquarius/commit/2d83c08ad55c60b705057a661a04340d4d5bd366 , can you confirm ?

**Comment by KatunaNorbert** [comment]
Tested and all assets have chainId now.
But now we got more assets on multinetwork for the following networks:

- Ropsten:  multinetwork(272)        main(263)
- Rinkeby:   multinetwork(14161)    main(14061)

Mainnet and BSC looks fine.


Also there is a problem with Polygon.  I don't get any assets

**Comment by alexcos20** [comment]
We have removed some constraints or relax them (ie:  2020-01-01 was not a valid datePublished, because it was not containing the time as well)  .  That's why you see more.

Investigating Polygon now

**Comment by alexcos20** [comment]
Polygon is broken indeed

aquarius_1         | 2021-07-08 09:54:58,502 - aquarius.events.processors - INFO - Process new DDO, did from event log:did:op:b27E48a56CD372355918192A46052Cef012Cc07b, sender:0x4D156A2ef69ffdDC55838176C6712C90f60a2285, flags: b'\x01', block 11260525, contract: 0x80E63f73cAc60c1662f27D2DFd2EA834acddBaa8, txid: 0x47b8efffdc4799ca549daa87a7c845be321314671fdd4dcd81cbeffe22c54ed5, chainId: 137
aquarius_1         | 2021-07-08 09:54:58,502 - aquarius.events.processors - DEBUG - checking allowed publishers: 0x4D156A2ef69ffdDC55838176C6712C90f60a2285
aquarius_1         | 2021-07-08 09:54:58 40cc8bb30de2 root[9] INFO Schema: /aquarius/aquarius/ddo_checker/schemas/metadata_remote_v0_6.json
aquarius_1         | 2021-07-08 09:55:18,903 - aquarius.events.events_monitor - ERROR - Error processing create metadata event: 
aquarius_1         | event=AttributeDict({'args': AttributeDict({'dataToken': '0xb27E48a56CD372355918192A46052Cef012Cc07b', 'createdBy': '0x4D156A2ef69ffdDC55838176C6712C90f60a2285', 'flags': b'\x01', 'data': b']\x00\x00\x00\x02\xf3\x0c\x00\x00\x00\x00\x00\x00\x00=\x82\x80\x17\x1c\x17\x90\xc7\xc1M\x80\x8f\xacNjzFv\x87\x01\xf86q\x1c\x98))\xe0\r\x9f#e\xdd[\x0bL]\x97gk\xc5\xe8^\xc9\xf0\xd9\xf8\x186\x11\xfd\xf6*<\xdf\xc1\xea\x18>\xcf\xddd\nm\xa0R$_\xcb[\x88\xc7\xc2\xb36\xffKiqq#\n\x8eAv\x80DAHJ\x8f\x16\xb4Y\xa8\xe7\xe2\x81\xbbo\xf5z\xae9\x9c\xa5vs\xcfUry\xe2\xdeo$d\xc7\xe20\xfd\xf7\xd5\x00"\xdf\x8cJ\x94B\xb7\x91\xb4,J\xbe\xb3l8\x05\x8d\xa74\xaa%\xcb\x86\xa4\xad\x8d\xf8\x06]\xcb\x13\x9c\x93\xeb\xf6\xd6\xe1\'\xcf\xbe+\\\x19{\xaa\x86\x97\xbb\xc9\r\x08\xeb\x8e[o\xcc\xb6\xdey\x98\xfa\x1c\xb3o\x90\xe74R\x95\x04\xc9N\xce\x1eA\xf6\xd69"\x00TI\xf0"85\x03\xf9\xd1\xb5fr\xb1\xfd5g\x91>\x8e&\x18S\x14\xf2\xb1\xfc(\x9f0\xcc\xb2\x1e\xd3\xc9\xce;\xc4\xdc\xd7\xa9\x07O\x10J\x08\t\xb3\x9f\x1eqo\x822\x12\x8c!\xf6\r\x9fF\xda\x19?\xdcn\x19\xf2\xb5\x9b\x86\xb4\xe4\x08-\xde\xce8\xfa]o\xb5M\xc7\xc30\x95\xfcY\x17w\xf7\xec{\x7f\xab\xc4\xa7\x02\x81\xfc\x86\x8d\xc1\\\x91C\'\x18`\xabh\xae\\R\x9e\xbe+=Q\xaa\xdc\xe1\xd1\xff3m"\x17\xb5#:\xde\x11N]\x84W1\x1d\xce\xa3\r\x8eS\xb5o#\x0e8o\x87RP\n\x99n\x89=9\x9f*\xc1\xd08V\x94u\xc0\xf4\x17\x8d\xcf3\xb2\xb6n\xe0\xb21\xeb\x19\xf3\xaf\xe9\xb4d\xd9\xe9z\xc3\xa2\xdc\xc0\x92{\x9b\xd33\xf2\x88\x81R\t\x9f\x00(\x94~\xbc\xbe\x92\x9c1n\xf1?\x15\xf91\x06\x9f\xb6D\x9da\xcf\xc2lN\x0fG\xfa\xd1\xa08\x19snKu\x992\xb4\x98\x03\x1c\xd8\xfd\x14\xd3X\xc6\xdc>\xf0\x9a\xdf\r\x8e\xbc0\xa8\r\x9e\xads\xa3\x1cE]s\xe7\x95\xed\xb4\x02\xc2p\xf0\x84\xc4\x04\x86\xc8\xbc\xf1\xee\xe9\xda\xed\x83F\xb7\xc8X\x1d\x82\xa0\xae\xe8\xd4\xbe\xa9\xa7\xcc\x02P$\xc0V\x88)b\x7f`v\x96\xdc\xac\x97\x95\x168\xb6.\xd7\x80ZJ\xd3\xa8\x95\xf5$\x83F\xca\x96\xaa\x1eg\x18\xe9]\xad\xacY\x7f\xd8\xfc\x19B\xe9\x9c.\x0eN\x11\x94c\xda\xf8\xbc\x9bm\xf7$\xc0\x1ch\xd0\x85\x99\xd5\xe6]\x8f$\x16\'l\xed\xad\xa0Nu\xcc\t\x1b\x8b\xe9\xb9T\xf0\xefq\x7f\xe5\x1f\xcd\x87\x08\x0c\xf8\x9f\xdff \xf0\xd1\x18\x17\xef\x94g\x81W\'R\x9f\x16o\xc8\xe5#\x91y\xba\xc5\x96\xb2\x9d\'\xb2C\x95\x9aOR\x93T\xf1\xe29^77!\xb1\xcb\xbby\x94\x95\x16\t\x83w\xed\x04\xb4>\xa7\xc1-b|\x1d1\xcf\xcaz\x01I\xee\x1a\x87\x98Iw\xc4\xfa]\xe3\xcaM@\xcbA\xf8\xacR\xb9\x8eP\x00\xa1M\x84\xcc\xcc\xf9\x8b\x04\xe6h7\xa0\xef\xd4t"\xbe\xd5CE\xf8-nc\x9f\xa1\x95\xd9\xa5\xd2\xc7(\x9aTaz\xd7V\x06Y\xf5\xaf\xbc\x07\x16\x02P\x0672v\x8e\xaf\x98\'_|\xe9\x9f\xcb@\xf6l\xef?&\x9e\x1f\xe0\xd4\xe2@v&b9\xb0\xac5^\x06\xb9$\xc5A\xeb1\xbd\xb5F\xef@R\x1a\xd4f#\x0b\x13\xedJ\x14\x8a\xcfD\x97s&M\x86\xb6S+!\n\x9e!!\x99o}(_@\xb8;\xb4\x8c\xd4\\>\x18G\xea\x1a\xad\xde\xe2\xcc\rT\xbbzg\x15\xb9w.1\xe3\xe3\xae\x05j>G\x8aEl\x07\x81o\xcf\xc7\xe1\x1eq\xd0\t\xbf\x11\x1f\xf4\x8e\x95h\x84\xeb\xe5\r\x92(\xe5 ~\xd7\x8a\xa7\xa9\x87\x99\xabyiX\xc3\xf12\xb1,\x15rV\xb5\x9e9\xf8\x9bB\xc4\xd6\x8c\xfa \x7fr<\xfb\xe3\xc2Q\xceq\xccDm\xb7\x0ce\x10\xf4\xbaJo\xdaL\tV\x0f\\\xb8\x0f\nc\xbc}M\x9d\x90\xd8\x85\x8d\x18\xc8$at\x9c\xfb+\xd8\xf2\x7f\x9bkaK\xcb9\x8f?Pj\x1e\xb8\xdb0\x0b\x98\x80\xd8F<HF\xf1X\xef\x0cVi\xfa\x8a\x04\x80\xc5\xca\xc2\x03q\xf1\xc2\xf7~\x84&\x01\xb9u\x1b}\xdbU\xe00y8~\x1bQ\x887\xbe\x1f\x92JL!\x12\xde\x1eaw.\x93\x02\xca\x02$\xff\xc17\\\xa9\xfe\x9f!\xee\x00\xd8AQ\xe6 R\x14\xf5\xcb!\x82s;\x15\xe5\xe67\xca\x0e8\x1b\x01\xe3\xca\x0c\xdb\x01"[\xbb+n\xca34&\x83V\xf0e]\x89\xa8$\xda\x9a\x9e\x89<\xd7`x\xaf\x90V\xe5V\x1dG_\xae\xd3\xa7\x01\xbb\xba\xfe\xd9\xe8=\x1a\x11\x05\xa7\x0e5\x88\x06\xfa#h@ \x15\x85\x958\x17\x1d\x91oI\x83\xe9w\xcd6\xe9+Tx\xdawx\x94\x8di\x0e@\x1dA\xbc\xc7\xc2\xc7\xb0\x88\xb6A\x04\xaf\x06@\xa7 4\x8fp\x81%&\xd4=\x0e\xa4\x12\x97oW\xadZ\xbc\xc6\x13\xd6}\xa7\xec\xd0\x94\xa1\xdf\x1561\x99\x92|G#I\xb1\x12\xe4K2\xbb\x9d\xfc\r!\n\x02\xdb\xc5\x87\xa1\xec\\S\x9b\x91\xdf\xfc\xac\xb6\xc0\xc3\xbe\xcc!7o\'\x10\x9f\x80\xc4\xfaq\xc8|h\xa5s-T\x7f\r\r\xde\xaa\xbe|\x95Jc\rpEV\x15\xa1\xecA\xd8\x9f\xc5\x0cK\xc6\xa6+9\xc6\xf9\xb9\xea;H\n$\xf2a\n\x01\xa1\x99\xd7{OD\xa5\xed\xcd\x83*m\x8a\x17\x07o\xcc\x1d\xd0\xf3z~\x1a<U2w\x8a\xa1N\x0e\xd6\x8d_jgd\x02\x80\x81\xed\xc1%b\x94\xc0\x86\xc4\x0cN\xb3\x9a\xc4RD\xcf\xfc\xea|\x94e\xf7O[\x84\xf2M\xf0WF&E\xe6j\x9d5\xc2uV\xc9_\xd31&\xf8\xda<[c\xb5x\x95\xb0\xa8\xfcH\x1c '}), 'event': 'MetadataCreated', 'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0x47b8efffdc4799ca549daa87a7c845be321314671fdd4dcd81cbeffe22c54ed5'), 'address': '0x80E63f73cAc60c1662f27D2DFd2EA834acddBaa8', 'blockHash': HexBytes('0x12dee697c11b0c34e044b5f035c1d14ac71b96405aac7079e388e3d47b080a75'), 'blockNumber': 11260525})

**Comment by alexcos20** [comment]
fixed

**Comment by KatunaNorbert** [comment]
Just tested now, all networks are looking good

**Comment by alexcos20** [comment]
closing this
