### ISSUE TITLE
Fix missing content in Aquarius py module

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/aquarius#517]
**Is your feature request related to a problem? Please describe.**
[Read the docs](https://github.com/oceanprotocol/readthedocs) parses the source code of Aquarius and generated `.md` files. The generated markdowns are rendered here: https://docs.oceanprotocol.com/references/read-the-docs/aquarius/. Some of the modules show `No content present` as there are no doc string the source code.

**Describe the solution you'd like**
Remove `No content present` by adding documentation in the source code.

**Comment by calina-c** [comment]
Hi, Akshay! I'll throw this back into "In progress". It seems like the strings have been added, but they look kind of chunky in the docs. Can we format them somehow?

![Screenshot 2021-09-02 at 08.11.38.png](https://images.zenhubusercontent.com/5795cf04e40e5714b16c76c5/1e7bed55-c88b-4d2a-89e6-8df9d89312c2)

**Comment by akshay-ap** [comment]
hi @calina-c , fixing this is tricky. The docstrings for documenting REST api follow `Swagger` specification format. The tool used to generate Aquarius read-the-doc (py module docs) understand only standard python docstrings and not `Swagger` spec. So, there is no way (at least that I know of) to make both Aquarius Swagger REST api and Py docs look good.

Same is the case for Provider: https://docs.oceanprotocol.com/references/read-the-docs/provider/ocean_provider/routes/consume

Possible solution:
Remove Aquarius py module  docs and Provider module py docs.

@trentmc Do you have any suggestions?

**Comment by trentmc** [comment]
> @trentmc Do you have any suggestions?

Yes. Don't even show the DDO here. Instead, say "it follow the structure specified at (link) https://docs.oceanprotocol.com/concepts/did-ddo/ with top-level fields 'context', 'id', etc. 

DRY:)

**Comment by AnaLoznianu** [comment]
@akshay-ap Do we have updates on this issue?

**Comment by akshay-ap** [comment]
hi @calina-c , we have removed the py docs for Aquarius and Provider. So, we can close this issue now.
