### ISSUE TITLE
Make instructions more clear

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#523]
It might be cumbersome to run multi network aqua, so let's try to improve the README

**Comment by kremalicious** [comment]
- image would help for multi network to communicate that there's Aquarius and multiple indexers
- lots of env vars in main readme, ideally instructions should follow the default use case "I want to run Aquarius and have it index all production networks"
- main readme could also just provide overview what needs to be done, and the rest handled in `deployment/README.md`
- `deployment/README.md` is super long and has lots of steps and unhelpful big blocks of log output, the `.yml` code blocks could be moved into their own files in `deployment/` and just linked
