### ISSUE TITLE
Update the readme file for the elastic search endpoint

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/aquarius#536]
Linked issue https://github.com/oceanprotocol/market/issues/719

Elasticsearch cannot return more than 10000 results for a given query.  This limitation should be clearly stated in the README and code comments for any aquarius endpoint that uses elasticsearch.

**Comment by DMats** [comment]
I updated the description to better explain the goal of this issue

**Comment by calina-c** [comment]
Added 507 response in docstring. Will be updated in docs once the new version of Aquarius is used.
