### ISSUE TITLE
Aquarius query returns 503 "Service Temporarily not available"

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/aquarius#558]
Here's the query https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo

**Comment by alexcos20** [comment]
Can you try https://aquarius.oceanprotocol.com/api/v1/aquarius/assets/ddo/did:op:0f5A4C51Dd71C7FB8D5D61e5B56C996681e4302F ?

**Comment by TimDaub** [comment]
that works, but with the URL in the title I used to get a list of all DDOs. I now stopped using https://aquarius.mainnet.oceanprotocol.com and implemented a function to crawl aquarius.oceanprotocol.com using the ddo/query endpoint.

**Comment by alexcos20** [comment]
I know :(.  We are updating them asap

**Comment by TimDaub** [comment]
To inform the tasks, here are some questions I want answered:

- What instances are running where and what software versions
- Who can I contact if an instance has a problem?
- How does the ddo/query endpoint work exactly and what is the query language syntax?
- For parameters like "offset", "page" etc. A short description of what they do
- Why does page start at 1 and not zero?
- What endpoints shall I use long term vs short term? I saw that e.g  the /ddo endpoint is gonna get deprecated
- What's the exact data model that is returned from e.g. a /ddo endpoint

What I still don't understand: In v3.0.0, it says that /ddo should list all data set meta data. But for both the mainnet instance and the new instance they return a 503.

Is this 503 an actual server error that and is its occurrence isolated to today? Or is it permanent given that you've made changes?


Finally:

With RPI, I'm also crawling data from BDP and their instance. From my understanding, it is below v3.0.0.

In the future to avoid chaos: Is there any plan to reduce the fragmentation of aquarius versions? E.g. what is stipping BDP from upgrading?

**Comment by md00ux** [comment]
@TimDaub ,

Main **Aquarius** instance (multichain):
https://aquarius.oceanprotocol.com 
- currently running v3.0.0 (it will be upgraded soon to v3.0.2
-this endpoint will be used long-term, all endpoints aquarius.<network>oceanprotocol.com can't be used.

Meanwhile, the docs were updated:
https://docs.oceanprotocol.com/references/aquarius/

- release notes for Aquarius
https://github.com/oceanprotocol/aquarius/releases

In case of any issue on accessing our services, you can open an issue here on Github in the corresponding repo and/or contact us on other channels (eg. Discord).

**Comment by TimDaub** [comment]
Thanks.
