### ISSUE TITLE
https://aquarius.rinkeby.oceanprotocol.com  gives 503

### ISSUE THREAD

**Issue by aman-rac** [oceanprotocol/aquarius#566]
**Describe the bug**
https://aquarius.rinkeby.oceanprotocol.com is giving a 503 Service Temporarily Unavailable

**To Reproduce**
1. Go to https://aquarius.rinkeby.oceanprotocol.com/

**Expected behavior**
Aquarius's root endpoint's response

 - Browser : chrome

**Comment by md00ux** [comment]
Please use https://aquarius.oceanprotocol.com .
This is the main Aquarius endpoint.

All endpoints using this name format are stopped.
 ```shell
aquarius.<network name>.oceanprotocol.com
```



You can find more details about this change here (section **Multi-Network Aquarius**)
https://blog.oceanprotocol.com/ocean-makes-multinetwork-even-simpler-c3ec6c0cbd50

**Comment by calina-c** [comment]
We have updated the networks page in the docs, as well: https://docs.oceanprotocol.com/concepts/networks/
As @md00ux said, there is now a universal multi-chain Aquarius.

@aman-rac can we help you with anything else? If not, I will close this ticket.

**Comment by calina-c** [comment]
Closing this. If something else is needed, let us know.
