### ISSUE TITLE
Stick to semantic versioning, pretty please

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#571]
The latest `v3.0.2` starts in its release notes (while changelog.md seems abandoned?) with "Breaking changes" yet it was released as a patch release. If there is a breaking change PLEASE follow semantic versioning and bump accordingly as to communicate to outside developers if they should act or not. As outside dev I would now assume I can safely update my instance cause it's just a patch release, only then to find all the breaking changes.

Breaking change means a new major version. Here's a reminder from https://semver.org:

> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards compatible manner, and
> PATCH version when you make backwards compatible bug fixes.

This issue is just a reminder as there is no action possible now, just for the next release.

**Comment by calina-c** [comment]
1. Should we also add changelog.md into the mix? From what I know, it is abandoned. But if we need to reactivate it, we will.
2. At the time I added the tag, the release process was still unclear, and the changes to the release process now DO contain the mention that breaking changes warrant major version changes. However, the release was already created by that point.

**Comment by calina-c** [comment]
@kremalicious We addressed this on Slack, and I've updated the readmes for Provider and Aquarius to reflect correct version numbering. I'm closing this issue, but if you want to resurrect changelog.md as part of this task, just reopen it and leave a comment.
