### ISSUE TITLE
Update elastic search to latest.

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#579]
We should move away from es 6.8

**Comment by AnaLoznianu** [comment]
Depends on es mappings

**Comment by mihaisc** [comment]
this should be done before "V4". What do you mean "depends on es mappings" ? They may need some changes but don't think it's a blocker. And in the first draft you can comment the mapping and just let es do it's own mapping . I presume the dependency is the final structure of the ddo/asset.

**Comment by AnaLoznianu** [comment]
@calina-c I don't remember the details of our conversation. Can you please shed some light on this ticket?

**Comment by calina-c** [comment]
Closed by https://github.com/oceanprotocol/aquarius/pull/628
