### ISSUE TITLE
Add Aquarius V4 smart contracts support

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/aquarius#582]

**Comment by calina-c** [comment]
@AnaLoznianu @alexcos20 is this refering to the ocean-contracts release issue? Otherwise, we do support and work with v4 contracts in Aquarius already. But I will leave it open i it is about ocean-contracts.

**Comment by AnaLoznianu** [comment]
@calina-c This refers to adding support and working with V4 contracts. Feel free to close if it's finished. Also for the ocean-contracts release issue please open a bug if there isn't one opened already.

**Comment by calina-c** [comment]
Closing since unrelated to the contracts release.
