### ISSUE TITLE
Process the state Changed Event in Aquarius

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/aquarius#623]
Contracts now emit an event when the metadata state changes. If an asset has any other status than "Active", delete it from the Aquarius cache (i.e. from Elasticsearch)

**Comment by mihaisc** [comment]
Not sure about this, based on this https://deploy-preview-783--docs-oceanprotocol.netlify.app/concepts/did-ddo/#state  it should be removed only in case state is `3` . In this state provider should refuse consumption as well.
For state `4` `Aquarius` doesn't need to do anything, `Provider` needs to refuse consumption
Not sure what implications there are for the rest of the states
