### ISSUE TITLE
ddo.purgatory is missing

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#669]
The enhanced DDO response should include `ddo.purgatory` as [outlined in the spec](https://github.com/oceanprotocol/docs/blob/feature/ddo_v4/content/concepts/did-ddo.md#purgatory) yet newly published assets against v4 are missing this in the response.

This is blocking https://github.com/oceanprotocol/market/issues/953

**Comment by claudiaHash** [comment]
Using the changes done in here, we discovered a bug: the assets published before these changes were deployed are still missing the `ddo.purgatory` attribute

**Comment by AnaLoznianu** [comment]
@calina-c Please see @claudiaHash's message

**Comment by calina-c** [comment]
Do we need to migrate the published assets? Technically, if no purgatory exists, it should be treated like purgatory state = false.

**Comment by claudiaHash** [comment]
I think this approach could lead to some inconstancy in the future when we use asset metadata on market, I'm not sure is the best one. @kremalicious

**Comment by calina-c** [comment]
"Official" answer from Alex: delete the ES instance, restart the aquarius deployment and reindex. This will reindex the old assets and the purgatory key will be there.

**Comment by kremalicious** [comment]
bump. Anybody acted on this?

**Comment by claudiaHash** [comment]
@md00ux just fixed it so I think it can be closed

**Comment by kremalicious** [comment]
all good, thanks everyone!
