### ISSUE TITLE
ddo.purgatory.state returns a string

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#675]
As [per the spec](https://github.com/oceanprotocol/docs/blob/b1750d01638c8ec249a9157127f7bd57d38b4392/content/concepts/did-ddo.md#purgatory),`ddo.purgatory.state` is supposed to return a boolean, but in all responses it puts the boolean in a string. 

Any reason for that? If there is some technical reason for that we ned to update ocean.js & market, as both assume a boolean here.

**Comment by calina-c** [comment]
I can add a boolean instead. I just added the same values as in v3. But I am currently blocked with barge, I can only add this ticket to the current sprint, not work on it per se.

**Comment by kremalicious** [comment]
> I can add a boolean instead. I just added the same values as in v3.

ok cool, thanks. Current implementation simply does not follow the spec which I linked to at exact purgatory place in #669, and again in here in the hope somebody clicks it.
