### ISSUE TITLE
Create a new configuration class to manage this servers configuration settings

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/aquarius#68]
## Expected Behavior

New config class to handle configuration settings via a config file and/or environment variables, for the server *provider*.

To define and setup the following settings from a config class using config file and or environment variables:
1. squid-py connections/addresses
1. azure setup
1. ocean db setup
1. provider server setup

Move the settings

1. provider.scheme
1. provider.host
1. provider.port

To a new section '[provider]' in the config file

## Current Behavior

The config parser from squid-py is used to manage this server's configuration data.

**Comment by eruizgar91** [comment]
#91
