### ISSUE TITLE
Replace event filtering

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/aquarius#710]
Polygon nodes hosted by Infura don't support event filtering. 

But aquarius uses event filtering here: https://github.com/oceanprotocol/aquarius/blob/v4main/aquarius/events/events_monitor.py#L385-L393

When running aquarius on Polygon or Mumbai hosted by Infura, the following error occurs: 
```
2022-02-17 19:12:01,644 - aquarius.events.events_monitor - ERROR - Error processing event: {'code': -32004, 'message': 'method not supported eth_newFilter'}.
```

This can be overcome by running your own Polygon/Mumbai node but this option may be difficult for some users.

Proposed Solution:
Replace event filter with a loop that calls `eth_getLogs` in 1000 block chunks, similar to ocean.py: https://github.com/oceanprotocol/ocean.py/blob/v4main/ocean_lib/web3_internal/contract_base.py#L352-L413

The chunk size should be configurable. Also, the referenced ocean.py code searches backward from the most recent block. Aquarius might want to choose the opposite behavior - searching forward from the oldest block.

**Comment by alexcos20** [comment]
it's necessary to search forward, because a DDO might change in a later block

**Comment by DMats** [comment]
#718 is merged so I'm closing this.

**Comment by alexcos20** [comment]
let's update v3 as well

**Comment by DMats** [comment]
This change was released in https://github.com/oceanprotocol/aquarius/releases/tag/v3.1.4 so I'm closing this issue.
