### ISSUE TITLE
Decrypt DDO fails

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/aquarius#713]
I tried to run couple of times the integration tests from ocean.py and the some of tests that publish the DDO on chain fail randomly. The issue is that the same tests worked before.

I paste here the error logs:
- Longer version:
`Traceback (most recent call last):
  File "/aquarius/aquarius/events/events_monitor.py", line 233, in handle_regular_event_processor
    event_processor.process()
  File "/aquarius/aquarius/events/processors.py", line 209, in process
    asset = decrypt_ddo(
  File "/aquarius/aquarius/events/decryptor.py", line 30, in decrypt_ddo
    response = requests.post(provider_url + "/api/services/decrypt", json=payload)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='myprovider', port=8030): Max retries exceeded with url: /api/services/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8aec922100>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2022-02-24 12:51:22,027 - aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: HTTPConnectionPool(host='myprovider', port=8030): Max retries exceeded with url: /api/services/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8aed4665b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
event=AttributeDict({'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0xb08d55c1d2172891c390c1ef1f63817fff1e963247fb52c490e9e4e200e2935b'), 'blockHash': HexBytes('0x957c50f538af656a6b50f6026ee8d5d3819d5ed9df502f4baa727d5d509300f1'), 'blockNumber': 138, 'address': '0x7358776DACe83a4b48E698645F32B043481daCBA', 'data': '0x000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000160f8929916089218bdb4aa78c3ecd16633afd44b8aef89299160000000000000000000000000000000000000000000000000000000000000000000000062177f44000000000000000000000000000000000000000000000000000000000000008a0000000000000000000000000000000000000000000000000000000000000016687474703a2f2f6d7970726f76696465723a38303330000000000000000000000000000000000000000000000000000000000000000000000000000000000019f8929916089218bdb4aa78c3ecd16633afd44b8aef89299160000000000000000000000000000000000000000000000000000000000000000000000000000019f8929916089218bdb4aa78c3ecd16633afd44b8aef8929916000000000000000', 'topics': [HexBytes('0x5463569dcc320958360074a9ab27e809e8a6942c394fb151d139b5f7b4ecb1bd'), HexBytes('0x000000000000000000000000be5449a6a97ad46c8558a3356267ee5d2731ab5e')], 'type': 'mined', 'removed': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1234, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1280, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1229, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 948, in send
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8aed4665b0>: Failed to establish a new connection: [Errno -2] Name or service not known`

- This one is shorter
`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='myprovider', port=8030): Max retries exceeded with url: /api/services/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8aec83ea90>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

`aquarius_1         | 2022-02-24 14:07:57,469 - aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: Provider exception on decrypt DDO: b'{"errors":{"signature":["Invalid signature provided."]},"message":"Validation error","success":false}\n'
`

**Comment by alexcos20** [comment]
who is "myprovider" ?  do you a DNS record or entry in /etc/hosts on aquarius container?

**Comment by alexcos20** [comment]
who is "myprovider" ?  do you a DNS record or entry in /etc/hosts on aquarius container?

**Comment by calina-c** [comment]
@mariacarmina can you please give some more detailed instructions on how to reproduce this? From yesterday's discussions, I understood that consume tests fail starting with the second run after barge pruning. I have run the consume flow test 3 times without failure. This means I can not reproduce the issue, so I need more details.

**Comment by mariacarmina** [comment]
I have tried to run test_data_service_provider.py and it failed for me at test_initialize and test_fileinfo.

**Comment by calina-c** [comment]
@mariacarmina I ran test_data_services_provider.py 3 times, no failure.

**Comment by mariacarmina** [comment]
I test as normal, with pruned barge and still getting this error `aquarius_1 | 2022-02-24 14:07:57,469 - aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: Provider exception on decrypt DDO: b'{"errors":{"signature":["Invalid signature provided."]},"message":"Validation error","success":false}\n`, due to the fact that provider apparently doesn't seem to call the decrypt endpoint properly. When this error ocurrs, the only log from provider is this `ocean_provider.run[14] INFO incoming request = http, POST, 172.15.0.5, /api/services/decrypt?`, but when the test work all the logs are showing.

**Comment by mariacarmina** [comment]
One problem in aquarius was that the `dataNftAddress` was not included in the signature as is specified in the provider rules for `DecryptRequest`. By that, I could extract more logs from provider and it seems to fail at the signatures.
`aquarius_1         | 2022-02-28 13:38:42,430 - aquarius.events.decryptor - INFO - provider URL: http://172.15.0.4:8030
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.run[16] INFO incoming request = http, POST, 172.15.0.5, /api/services/decrypt?
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO ['transactionId', 'dataNftAddress', 'decrypterAddress', 'chainId', 'nonce']
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO value: 0xea2bfeb627b91be315e4c3ef4da0a8da41c2c6a4853c930498f39168e63f73fc3a314ac49a2f9fd50df4cb400d5c5c527048ef9a554615f1beefe09143e4cdf11c
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO tx id: 0x80c4318a97da0031e3536fcdfc5e5358b9b63deb444905a47eacdfe7063542d1
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO data nft address: 0x2A2ACa5c39496a48912c339eb3c5d1Ba31a69602
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO decrypter address: 0xA78deb2Fa79463945C247991075E2a0e98Ba7A09
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO chain id: 8996
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO nonce : 1646055522.420098
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO tx id: 0x80c4318a97da0031e3536fcdfc5e5358b9b63deb444905a47eacdfe7063542d1
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO original msg: 0x80c4318a97da0031e3536fcdfc5e5358b9b63deb444905a47eacdfe7063542d10xA78deb2Fa79463945C247991075E2a0e98Ba7A098996
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.validation.provider_requests[16] INFO first arg: 0x80c4318a97da0031e3536fcdfc5e5358b9b63deb444905a47eacdfe7063542d1
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.utils.accounts[16] INFO nonce : None
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.utils.accounts[16] INFO nonce : 1646055522.420098
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.utils.accounts[16] INFO message : 0x80c4318a97da0031e3536fcdfc5e5358b9b63deb444905a47eacdfe7063542d10xA78deb2Fa79463945C247991075E2a0e98Ba7A0989961646055522.420098
provider_1         | 2022-02-28 13:38:42 875a2f31ee66 ocean_provider.utils.accounts[16] ERROR Invalid signature 0xea2bfeb627b91be315e4c3ef4da0a8da41c2c6a4853c930498f39168e63f73fc3a314ac49a2f9fd50df4cb400d5c5c527048ef9a554615f1beefe09143e4cdf11c for ethereum address 0xA78deb2Fa79463945C247991075E2a0e98Ba7A09, message 0x80c4318a97da0031e3536fcdfc5e5358b9b63deb444905a47eacdfe7063542d10xA78deb2Fa79463945C247991075E2a0e98Ba7A098996 and nonce 1646055522.420098. Expected: 0xa78deb2fa79463945c247991075e2a0e98ba7a09 but got 0x574cd2abfbd637f46f15196d95e1432f2527cdbc
aquarius_1         | 2022-02-28 13:38:42,443 - aquarius.events.decryptor - INFO - status code:400
aquarius_1         |  content: b'{"errors":{"signature":["Invalid signature provided."]},"message":"Validation error","success":false}\n'
aquarius_1         | 2022-02-28 13:38:42,443 - aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: Provider exception on decrypt DDO: b'{"errors":{"signature":["Invalid signature provided."]},"message":"Validation error","success":false}\n'`

**Comment by mariacarmina** [comment]
I have discovered the problem, the problem is that db_nonce that is extracted from a certain user_nonce table from provider codebase. If that nonce exists, it will throw the error for invalid signature. Just for testing purpose, I've set db_nonce to None and all the tests related to publishing are passing, so I suspect that db_nonce is the problem. If I start with a fresh barge, the error doesn't occur (because at the beginning the db_nonceis None . But if I will test multiple times, the error appears and also the db_nonce is modified and even greater that the actual nonce sent from aquarius payload when it call decrypt endpoint.

I suspect that there is a clock difference between aquarius who is sendinf the payload and the redis caching db from provider (I have also tried with `datetime.utcnow.timestamp()` in both components but still the db_nonce is higher).

**Comment by mariacarmina** [comment]
Besides those investigations, I have changes all the ganache wallets just to make sure that all the private keys do not collide when sending transaction (the nonce cannot be updated properly). Now all the tests seem to pass and I will create PRs for aquarius & provider as well.
