### ISSUE TITLE
Hash check failed during the processing of a MetadaCreated event in rinkeby

### ISSUE THREAD

**Issue by md0x** [oceanprotocol/aquarius#750]
During the processing of a MetadaCreated event, aquarius has raised the following exception in rinkeby. As a result the asset hasn't been indexed :

[aquarius_error.txt](https://github.com/oceanprotocol/aquarius/files/8287241/aquarius_error.txt)

The description of the asset was the following (including a quotation dash ―):
Ocean Asset NFT ― OCEAN-NFT
This NFT represents an asset in the Ocean Protocol v4 ecosystem.

https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:0e6cd9caa1b22978d290b4b619b224ae1e940d576194e9e5c36eae3ea4aef0e4

[Transaction 1](https://rinkeby.etherscan.io/tx/0xba7645d6ff1ced7b8f6dfd027dba102ac6ddf52191162396c21a922c3aac61cf)
[Transaction 2](https://rinkeby.etherscan.io/tx/0xd1a209384954b1049dbb52a81a27868b5cd47cd16c96d8af9579cbc8547e1264)

**Comment by DMats** [comment]
I looked into this but I wasn't able to figure it out.  

Here's the two transactions decoded:
https://ethtx.info/rinkeby/0xba7645d6ff1ced7b8f6dfd027dba102ac6ddf52191162396c21a922c3aac61cf/
https://ethtx.info/rinkeby/0xd1a209384954b1049dbb52a81a27868b5cd47cd16c96d8af9579cbc8547e1264/

**Comment by AnaLoznianu** [comment]
@md0x Can we close this, as that the Spanish characters fix is merged?
