### ISSUE TITLE
Aquarius not Cache asset published on Mumbai

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/aquarius#759]
**Describe the bug**
Looks like an Aquarius issue on Mumbai. Published [this asset](https://v4.market.oceanprotocol.com/asset/did:op:6a2d03759289837255c9db43cf9f052af562a857361dd6b6192281efe1c8399d) 2 hrs 45 mins ago but still not visible in the market

[Transaction 1](https://mumbai.polygonscan.com/tx/0x7f427eb3f33b3618e42d213405e25ede33ad84f1918d3d1998adb21344ca5441)
[Transaction 2](https://mumbai.polygonscan.com/tx/0xb7318978d2c0eb98554a41d899cb5ea6df07e4164a209f129a0deec2a1ab58dc)

The response from Aquarius is `{"error":"Asset DID did:op:6a2d03759289837255c9db43cf9f052af562a857361dd6b6192281efe1c8399d not found in Elasticsearch."}`

**Comment by mihaisc** [comment]
this may not be an aquarius bug. [subgraph nft](https://v4.subgraph.mumbai.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20nft(id%3A%220xa86328d8e330fc6f5499364e830540a8622e1d32%22)%7B%0A%20%20%20%20id%2C%0A%20%20%20%20providerUrl%2C%0A%20%20%20%20%20symbol%0A%20%20%7D%0A%7D) shows that provider url is wrong for some reason.
