### ISSUE TITLE
Update logic to support new DID/DDO's

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/aquarius#77]
It would be necessary to udpate the business logic to support the new DID/DDO's entities. The changes to apply are:

- [x] Support internally the DID/DDO models [see DDO example](https://github.com/oceanprotocol/squid-java/blob/master/src/test/resources/examples/ddo-example.json)
- [x] GET /api/v1/aquarius/assets/metadata -- Update the method to return only the metadata entry
- [x] GET /api/v1/aquarius/assets/ddo/{did} -- New method returning the complete DDO

- [x] Delete method POST /api/v1/aquarius/assets/metadata 
- [x] New method - POST /api/v1/aquarius/assets/ddo -- Create the DDO and the associated DID

- [x] Delete method PUT /api/v1/aquarius/assets/metadata -- Delete, we well use the 
- [x] New method  PUT /api/v1/aquarius/assets/ddo -- Actualiza datos del DDO

- [x] New method DELETE /api/v1/aquarius/assets/ddo -- Delete the DDO

- [x] Update method - GET /api/v1/provider/assets -- Devuelve todos los DID's

- [x] Delete method - GET /api/v1/provider/assets/metadata/query
- [x] New method - /api/v1/provider/assets/ddo/query -- DDO's Search

**Comment by eruizgar91** [comment]
#79
