### ISSUE TITLE
DDO filter/restriction based on wallet via RBAC

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/aquarius#779]
### Is your feature request related to a problem? Please describe.

To have a customizable way to filter or restrict DDO based on wallet for different market.
In some context some wallet would have different capabilities or same capability but at different intensity.
In the example of no connected wallet or some restricted wallet (not purge), aquarius would able to limit some data or remove some attribute.

### Describe the solution you'd like
Aquarius metadata query endpoint such as query_ddo, get_ddo n etc.  would have optional wallet address as querystring, body or header.
With rbac-server url set, rbac-server then could perform some filter or proxy the request to another API that does the filtering of DDO **right before respond return**. _This step would be skipped if rbac-server url are not valid._

Filter would be AND/OR the following:
1. Removing row or data
2. Removing attribute within object.

**Comment by alexcos20** [comment]
@soonhuat - can you check that PR and see if it suits your needs ?

**Comment by soonhuat** [comment]
@alexcos20 i think we need optional wallet address as querystring, body or header.
which is provided by market or sdk during the request, optional. 
so then rbac can act upon (sanitize) the payload based on wallet, thus, different user/wallet will have different behavior.

**Comment by alexcos20** [comment]
What if we pass all headers? then it's up to you

**Comment by soonhuat** [comment]
@alexcos20 yup, that could work
Then up to the market operator to extend the header for their use case

**Comment by alexcos20** [comment]
@calina-c ^
