### ISSUE TITLE
Update readme to explain how to create an isolated marketplace

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/aquarius#801]
As far as I can tell we haven't documented anywhere what steps are required to create an isolated marketplace. This is an important part of the process of setting up a marketplace for most people and I think it would be a good addition to the readme. 

- [ ] Depends on https://github.com/oceanprotocol/aquarius/issues/813

**Comment by calina-c** [comment]
We decided it's best to add this in the main docs. We'll talk next week and create instructions together.

**Comment by jamiehewitt15** [comment]
Once it's done in the main docs, we can just add a link to the documentation from the Aquarius readme. 

Relevant issue: https://github.com/oceanprotocol/docs/issues/1040

**Comment by AnaLoznianu** [comment]
Closing this as it will be done on the main docs.

**Comment by AnaLoznianu** [comment]
Closing this as it will be added in the main docs
