### ISSUE TITLE
Move "Running Aquarius locally, for development and testing" section into readme

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/aquarius#811]
One of the main things that I would expect to find in a readme is instructions on how to run Aquarius locally. These instructions are currently tucked away in `developers.md` which sounds like it's a document for maintainers. I feel like we would benefit from making the instructions on how to run Aquarius locally more prominent and moving them to the readme

**Comment by trentmc** [comment]
I think this is a great idea.

We actually had this in the datatoken ocean.py readme in early days of v3 development. As well as running provider locally. And running ganache directly. But then we decided to make the initial flow simpler by just having barge. 

I think it's still a good idea for the datatoken readme to use barge (status quo), and have a separate follow-on readme to run Aquarius locally (this ticket), and another follow-on readme to run provider locally (a ticket yet to be created)
