### ISSUE TITLE
Encrypted datasets can only use single key for multichain environments

### ISSUE THREAD

**Issue by ArseniiPetrovich** [oceanprotocol/aquarius#827]
**Describe the bug**
The `encrypt` endpoint takes `EVENTS_ECIES_PRIVATE_KEY` as the key for encrypting and decryption. In multichain installation separate installations of Aquarius should use separate keys for different networks.

**To Reproduce**
1. Install multichain environment separating RPC and NETWORK installation of aquarius
2. Realize that each NETWORK installation decrypts DDO that are encrypted with key from RPC, and there are no supply for multiple keys for RPC.

**Expected behavior**
Aquarius can use different keys on different networks.

**Comment by AnaLoznianu** [comment]
Thanks for raising this, but at this current moment, it is impossible from a technical perspective to have this solution integrated.

Thanks for your contributions!
