### ISSUE TITLE
Unable to restore nft state from "Ordering is temporary disabled" to "active"

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/aquarius#836]
**Description**
When nft state change from 4 (Ordering is temporary disabled.) to 0 (Active), event not processed because ddo exist and warning thrown.

**Describe the solution**
Add state update when processing `EVENT_METADATA_STATE`

**Comment by soonhuat** [comment]
@calina-c the PR will handling scenario of changing state from non-active to the new state, thus, could re-enable _Ordering is temporary disabled_

**Comment by calina-c** [comment]
@soonhuat should I close this ticket? The PR you submitted is merged, I assume it is the complete solution.

**Comment by soonhuat** [comment]
@calina-c yup, thanks
