### ISSUE TITLE
Add price in stats

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#853]
Using this [query](https://v4.subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0Atoken(id%3A%220x0ef5a069951db71840bbc3b15f572c6c6c682864%22)%7B%0A%20%20id%0AorderCount%0A%20%20fixedRateExchanges%7B%0A%20%20%20%20price%0A%20%20%7D%0A%7D%0A%7D) we can also easily fetch the price and orders. Adding the price is now feasible because we don't have any pools. 

```
 "stats": {
    "orders": 7,
    "price": 3.45
  },
```

We do the same query and update both price and orderCount on : `OrderStarted` , `ExchangeCreated`  and  `ExchangeRateChanged`  . Also maybe add a small delay in this function , not sure what the best approach would be. Basically after you get an event to wait a bit for the subgraph to update (maybe this is already there, didn't check)

**Comment by calina-c** [comment]
the subgraph update is there, yes.

**Comment by mihaisc** [comment]
Please paste the did

**Comment by jamiehewitt15** [comment]
did:op:b62d6359fd9c45ff3df50a82f8d3b89baf9ec60d3c8ecbe81a28934c0bba91b3

**Comment by mihaisc** [comment]
@jamiehewitt15 this is probably fixed in the refactor so we just have to wait for that https://v4-2.aquarius.oceanprotocol.com/api/aquarius/assets/ddo/did:op:b62d6359fd9c45ff3df50a82f8d3b89baf9ec60d3c8ecbe81a28934c0bba91b3

**Comment by jamiehewitt15** [comment]
That's this PR? https://github.com/oceanprotocol/aquarius/pull/928
