### ISSUE TITLE
Change `service` minimum

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#884]
https://github.com/oceanprotocol/aquarius/blob/70d57df0071d415130ebf2a663fa521448822a10/aquarius/ddo_checker/shacl_schemas/v4/remote_4.3.0.ttl#L50

Services min should be 0, you should be able to create an asset with no service.

**Comment by AnaLoznianu** [comment]
@mariacarmina I see a merged PR on this issue. Can we close it?
