### ISSUE TITLE
Nft owner not being updated

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#905]
Nft address :  [0xd74270dcd1f21544CcABbd3594Fbb68224d09e46](https://polygonscan.com/address/0xd74270dcd1f21544CcABbd3594Fbb68224d09e46) (polygon)
[Subgraph example](https://v4.subgraph.polygon.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0Anft%28id%3A%220xd74270dcd1f21544ccabbd3594fbb68224d09e46%22%29+%7B%0A++id%0A++owner%0A%7D%0A%7D&variables=%22%7B%5Cn++%5C%22owner%5C%22%3A+%5C%220x3e81aa994f774ee914d57946ddf2486ea7d42d65%5C%22%2C%5Cn++%5C%22pool%5C%22%3A+%5C%220x1394422b871d0fe64da7557df567c7cccd0c7ae9%5C%22%2C%5Cn++%5C%22poolAsString%5C%22%3A+%5C%220x1394422b871d0fe64da7557df567c7cccd0c7ae9%5C%22%2C%5Cn++%5C%22user%5C%22%3A+%5C%220x3e81aa994f774ee914d57946ddf2486ea7d42d65%5C%22%5Cn%7D%22)
[Market url](https://market.oceanprotocol.com/asset/did:op:bacc5d13e2eea5f4729ad12c05a543646476e8517bc27721575622f4cec23f7c)

**Comment by mihaisc** [comment]
no idea, @md00ux ?

**Comment by md00ux** [comment]
@mihaisc 
For Polygon, we are running  **oceanprotocol/aquarius:v4.2.0** (aquarius events)

**Comment by calina-c** [comment]
@md00ux @mihaisc my main assumption here is that we need dynamic blocks. The last step of dynamic blocks is handling those missing 2 assets we found. I'll talk about that with Alex today.

**Comment by AnaLoznianu** [comment]
We need to retest this issue once the aqua loop refactoring goes live.

**Comment by AnaLoznianu** [comment]
Tested this on the new aqua deployment(https://github.com/oceanprotocol/market/pull/1752) and it works as expected.

**Comment by AnaLoznianu** [comment]
Fixed by: https://github.com/oceanprotocol/aquarius/pull/943
