### ISSUE TITLE
Aquarius API gives CORS error

### ISSUE THREAD

**Issue by umang-usquare** [oceanprotocol/aquarius#916]
Hi there!

I am trying to render metadata on the browser using Aquarius API service. Aquarius has been set up for Polygon Mumbai network using Kubernetes and Elastic Search with AWS as a service provider. While fetching data, there appears a CORS error. I have tried using proxy as Nginx and it does show CORS error.

Is there something I am missing out here? Really eager to solve this issue.

**Comment by alexcos20** [comment]
This is a devops issue, not an aquarius issue.
Pls check your nginx config
