### ISSUE TITLE
Ocean Market Sales Count

### ISSUE THREAD

**Issue by Harky911** [oceanprotocol/aquarius#918]
In the Ocean market when there is a purchase of a dataset the sales count is not reflected.

**Comment by kremalicious** [comment]
all synced and Aquarius shows actual number now

<img width="488" alt="Screen Shot 2022-10-14 at 14 33 04" src="https://user-images.githubusercontent.com/90316/195859633-29b6f712-c8a0-4d01-9fca-b4982f3f4e90.png">
