### ISSUE TITLE
Aquarius not updating for assets on Polygon (mainnet not testnet)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/aquarius#920]
**Describe the bug**

I've seen symptoms in both Ocean Market and ocean.py. Here are three. (FYI publishing on Mumbai works; the problem is Polygon's _mainnet_.)

1. In Ocean Market, I went to an [asset that I published](https://market.oceanprotocol.com/asset/did:op:0dac5eb4965fb2b485181671adbf3a23b0133abf71d2775eda8043e8efc92d19) on Polygon >1 week ago. I clicked "edit". I made changes. I clicked "submit". It appears that the tx went through ok. But when I refresh the page, the changes are not reflected.
2. Using ocean.py as a library, publishing an asset on Polygon returns `None`. To reproduce: go through the flow in [this ocean.py#1007 comment](https://github.com/oceanprotocol/ocean.py/issues/1007#issuecomment-1276286245). It fails with `asset` being `None`.
3. Using ocean.py github repo, as a developer. 
   - First, checkout the [the "issue1007-none" branch](https://github.com/oceanprotocol/ocean.py/tree/issue1007-none) ([Here's the related PR](https://github.com/oceanprotocol/ocean.py/pull/1009).)
   - Then: `export REMOTE_TEST_PRIVATE_KEY1=<your Polygon private key>`
   - Then: `pytest tests/integration/remote/test_polygon.py`. This is a new test that I created to capture the issue. It will fail with `asset` being `None`.

Note: if I run (2) on Mumbai not Polygon, it works. Same for (3). 

**Related**

There were problems reported recently on Mumbai (Polygon testnet), and I believe @alexcos20 put in a fix today for Mumbai. There's a chance it's a similar issue, and fix, for Polygon.

**Comment by kremalicious** [comment]
Same issue as #918

**Comment by alexcos20** [comment]
aqua is syncing right now, will take some time to be up2date

**Comment by trentmc** [comment]
I'm still getting failures in the unit tests (symptom 3) reported above. 

`requests.exceptions.Rea[Uploading log.txt…]()Timeout: HTTPSConnectionPool(host='polygon-rpc.com', port=443): Read timed out. (read timeout=10)`

See attached log.

**Comment by trentmc** [comment]
Update: symptom (1) as reported in the issue description is now resolved. I'm assuming it's because Aquarius was updated.

Issue (2) and (3) have timeout issues, as reported above. I will move forward on this, with Alex's suggestion or some other workarounds. Will post updates here.
