### ISSUE TITLE
Add log message for assets that are not valid

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#933]
When an asset fails the shacl validation in the logs i see something like `Process new DDO, did from event log: ...` and then aquarius moves on with its life 😁 .
It would be nice to have something like `DDO with did ... did not match shacl version 4.1.0 ` or somethig like this.

Update: apparently in some cases it does this, even logs what is not ok, so it's easy to debug. Not sure why for some it didn't

**Comment by AnaLoznianu** [comment]
Retest this on the big refactoring @alexcos20 did on Aquarius.
