### ISSUE TITLE
Fix triggerCache endpoint

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#980]
1) add chainId
2) make sure that triggering actually works

**Comment by calina-c** [comment]
@alexcos20 chain_id is already added as far as I can tell. Can you please add details towards item 2 of this ticket?

**Comment by calina-c** [comment]
Problem is now the endpoint makes its own short retry queue (of length 1) and tries to process it.
What it should do: simply add to ES and return if successfully added to the queue

**Comment by calina-c** [comment]
Closed by https://github.com/oceanprotocol/aquarius/pull/1010
